// Code generated by protoc-gen-go. DO NOT EDIT.
// source: subtask/subtask.proto

package subtask

import (
	context "context"
	fmt "fmt"
	cmdb "git.fogcdn.top/axe/protos/goout/cmdb"
	common "git.fogcdn.top/axe/protos/goout/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 裸金属任务状态
type ServerTaskType int32

const (
	// 未定义任务类型
	ServerTaskType_UNDEFINED ServerTaskType = 0
	// 裸金属状态查询任务
	ServerTaskType_CHECK ServerTaskType = 1
	// 裸金属电源开关任务
	ServerTaskType_POWER ServerTaskType = 2
	// 裸金属初始化创建uuid任务
	ServerTaskType_CREATE ServerTaskType = 3
	// 裸金属安装任务
	ServerTaskType_INSTALL ServerTaskType = 4
)

var ServerTaskType_name = map[int32]string{
	0: "UNDEFINED",
	1: "CHECK",
	2: "POWER",
	3: "CREATE",
	4: "INSTALL",
}

var ServerTaskType_value = map[string]int32{
	"UNDEFINED": 0,
	"CHECK":     1,
	"POWER":     2,
	"CREATE":    3,
	"INSTALL":   4,
}

func (x ServerTaskType) String() string {
	return proto.EnumName(ServerTaskType_name, int32(x))
}

func (ServerTaskType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{0}
}

// 子任务执行结果
type SubTaskResult int32

const (
	// 失败
	SubTaskResult_FAILURE SubTaskResult = 0
	// 成功
	SubTaskResult_SUCCESS SubTaskResult = 1
)

var SubTaskResult_name = map[int32]string{
	0: "FAILURE",
	1: "SUCCESS",
}

var SubTaskResult_value = map[string]int32{
	"FAILURE": 0,
	"SUCCESS": 1,
}

func (x SubTaskResult) String() string {
	return proto.EnumName(SubTaskResult_name, int32(x))
}

func (SubTaskResult) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{1}
}

// 创建子任务实例请求
type CreateRequest struct {
	TaskId int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// cmdb的搜索条件
	CmdbSearchRequest *cmdb.ChooseHostRequest `protobuf:"bytes,2,opt,name=cmdb_search_request,json=cmdbSearchRequest,proto3" json:"cmdb_search_request,omitempty"`
	// 模板ID
	TemplateId           int32    `protobuf:"varint,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{0}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *CreateRequest) GetCmdbSearchRequest() *cmdb.ChooseHostRequest {
	if m != nil {
		return m.CmdbSearchRequest
	}
	return nil
}

func (m *CreateRequest) GetTemplateId() int32 {
	if m != nil {
		return m.TemplateId
	}
	return 0
}

// 创建子任务实例请求返回
type CreateResponse struct {
	// 子任务实例ID
	SubTaskId []int64 `protobuf:"varint,1,rep,packed,name=sub_task_id,json=subTaskId,proto3" json:"sub_task_id,omitempty"`
	// 返回的请求状态
	Status               *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetSubTaskId() []int64 {
	if m != nil {
		return m.SubTaskId
	}
	return nil
}

func (m *CreateResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 交维表导入后巡检子任务请求
type CreateServerCompareRequest struct {
	// 任务实例ID
	TaskId int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// cmdb的搜索条件
	CmdbSearchRequest    *cmdb.ChooseServerCompareRequest `protobuf:"bytes,2,opt,name=cmdb_search_request,json=cmdbSearchRequest,proto3" json:"cmdb_search_request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *CreateServerCompareRequest) Reset()         { *m = CreateServerCompareRequest{} }
func (m *CreateServerCompareRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServerCompareRequest) ProtoMessage()    {}
func (*CreateServerCompareRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{2}
}

func (m *CreateServerCompareRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerCompareRequest.Unmarshal(m, b)
}
func (m *CreateServerCompareRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerCompareRequest.Marshal(b, m, deterministic)
}
func (m *CreateServerCompareRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerCompareRequest.Merge(m, src)
}
func (m *CreateServerCompareRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServerCompareRequest.Size(m)
}
func (m *CreateServerCompareRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerCompareRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerCompareRequest proto.InternalMessageInfo

func (m *CreateServerCompareRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *CreateServerCompareRequest) GetCmdbSearchRequest() *cmdb.ChooseServerCompareRequest {
	if m != nil {
		return m.CmdbSearchRequest
	}
	return nil
}

// 交维表导入后巡检子任务请求返回
type CreateServerCompareResponse struct {
	// 子任务实例ID
	SubTaskId int64 `protobuf:"varint,1,opt,name=sub_task_id,json=subTaskId,proto3" json:"sub_task_id,omitempty"`
	// 返回的请求状态
	Status               *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateServerCompareResponse) Reset()         { *m = CreateServerCompareResponse{} }
func (m *CreateServerCompareResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServerCompareResponse) ProtoMessage()    {}
func (*CreateServerCompareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{3}
}

func (m *CreateServerCompareResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerCompareResponse.Unmarshal(m, b)
}
func (m *CreateServerCompareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerCompareResponse.Marshal(b, m, deterministic)
}
func (m *CreateServerCompareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerCompareResponse.Merge(m, src)
}
func (m *CreateServerCompareResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServerCompareResponse.Size(m)
}
func (m *CreateServerCompareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerCompareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerCompareResponse proto.InternalMessageInfo

func (m *CreateServerCompareResponse) GetSubTaskId() int64 {
	if m != nil {
		return m.SubTaskId
	}
	return 0
}

func (m *CreateServerCompareResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 裸金属子任务实例请求
type CreateServerRequest struct {
	// 任务实例ID
	TaskId int64 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// 裸金属任务类型
	TaskType ServerTaskType `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3,enum=subtask.ServerTaskType" json:"task_type,omitempty"`
	// 裸金属电源状态
	PowerState cmdb.ServerPowerState `protobuf:"varint,3,opt,name=power_state,json=powerState,proto3,enum=cmdb.ServerPowerState" json:"power_state,omitempty"`
	// cmdb的搜索条件
	CmdbSearchRequest *cmdb.ChooseServerRequest `protobuf:"bytes,4,opt,name=cmdb_search_request,json=cmdbSearchRequest,proto3" json:"cmdb_search_request,omitempty"`
	// 安装镜像文件的URL
	ImageFileUrl string `protobuf:"bytes,5,opt,name=image_file_url,json=imageFileUrl,proto3" json:"image_file_url,omitempty"`
	// 安装镜像文件的MD5
	ImageFileMd5         string   `protobuf:"bytes,6,opt,name=image_file_md5,json=imageFileMd5,proto3" json:"image_file_md5,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateServerRequest) Reset()         { *m = CreateServerRequest{} }
func (m *CreateServerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateServerRequest) ProtoMessage()    {}
func (*CreateServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{4}
}

func (m *CreateServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerRequest.Unmarshal(m, b)
}
func (m *CreateServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerRequest.Marshal(b, m, deterministic)
}
func (m *CreateServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerRequest.Merge(m, src)
}
func (m *CreateServerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateServerRequest.Size(m)
}
func (m *CreateServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerRequest proto.InternalMessageInfo

func (m *CreateServerRequest) GetTaskId() int64 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *CreateServerRequest) GetTaskType() ServerTaskType {
	if m != nil {
		return m.TaskType
	}
	return ServerTaskType_UNDEFINED
}

func (m *CreateServerRequest) GetPowerState() cmdb.ServerPowerState {
	if m != nil {
		return m.PowerState
	}
	return cmdb.ServerPowerState_UNKNOWN
}

func (m *CreateServerRequest) GetCmdbSearchRequest() *cmdb.ChooseServerRequest {
	if m != nil {
		return m.CmdbSearchRequest
	}
	return nil
}

func (m *CreateServerRequest) GetImageFileUrl() string {
	if m != nil {
		return m.ImageFileUrl
	}
	return ""
}

func (m *CreateServerRequest) GetImageFileMd5() string {
	if m != nil {
		return m.ImageFileMd5
	}
	return ""
}

// 裸金属子任务实例返回
type CreateServerResponse struct {
	// 子任务实例ID
	SubTaskId int64 `protobuf:"varint,1,opt,name=sub_task_id,json=subTaskId,proto3" json:"sub_task_id,omitempty"`
	// 返回的请求状态
	Status               *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateServerResponse) Reset()         { *m = CreateServerResponse{} }
func (m *CreateServerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateServerResponse) ProtoMessage()    {}
func (*CreateServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{5}
}

func (m *CreateServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateServerResponse.Unmarshal(m, b)
}
func (m *CreateServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateServerResponse.Marshal(b, m, deterministic)
}
func (m *CreateServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateServerResponse.Merge(m, src)
}
func (m *CreateServerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateServerResponse.Size(m)
}
func (m *CreateServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateServerResponse proto.InternalMessageInfo

func (m *CreateServerResponse) GetSubTaskId() int64 {
	if m != nil {
		return m.SubTaskId
	}
	return 0
}

func (m *CreateServerResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 完成子任务实例请求
type CompleteRequest struct {
	// 子任务实例ID
	SubTaskId int64 `protobuf:"varint,1,opt,name=sub_task_id,json=subTaskId,proto3" json:"sub_task_id,omitempty"`
	// 执行开始时间
	StartTime string `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 执行结束时间
	EndTime string `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// 子任务执行结果
	Result SubTaskResult `protobuf:"varint,4,opt,name=result,proto3,enum=subtask.SubTaskResult" json:"result,omitempty"`
	// 总共执行多少主机
	ExecuteCount int32 `protobuf:"varint,5,opt,name=execute_count,json=executeCount,proto3" json:"execute_count,omitempty"`
	// 执行失败多少台主机
	FailCount int32 `protobuf:"varint,6,opt,name=fail_count,json=failCount,proto3" json:"fail_count,omitempty"`
	// 执行成功多少台主机
	SuccessCount         int32    `protobuf:"varint,7,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CompleteRequest) Reset()         { *m = CompleteRequest{} }
func (m *CompleteRequest) String() string { return proto.CompactTextString(m) }
func (*CompleteRequest) ProtoMessage()    {}
func (*CompleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{6}
}

func (m *CompleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteRequest.Unmarshal(m, b)
}
func (m *CompleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteRequest.Marshal(b, m, deterministic)
}
func (m *CompleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteRequest.Merge(m, src)
}
func (m *CompleteRequest) XXX_Size() int {
	return xxx_messageInfo_CompleteRequest.Size(m)
}
func (m *CompleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteRequest proto.InternalMessageInfo

func (m *CompleteRequest) GetSubTaskId() int64 {
	if m != nil {
		return m.SubTaskId
	}
	return 0
}

func (m *CompleteRequest) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *CompleteRequest) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *CompleteRequest) GetResult() SubTaskResult {
	if m != nil {
		return m.Result
	}
	return SubTaskResult_FAILURE
}

func (m *CompleteRequest) GetExecuteCount() int32 {
	if m != nil {
		return m.ExecuteCount
	}
	return 0
}

func (m *CompleteRequest) GetFailCount() int32 {
	if m != nil {
		return m.FailCount
	}
	return 0
}

func (m *CompleteRequest) GetSuccessCount() int32 {
	if m != nil {
		return m.SuccessCount
	}
	return 0
}

// 完成子任务实例请求返回
type CompleteResponse struct {
	// 返回的请求状态
	Status               *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CompleteResponse) Reset()         { *m = CompleteResponse{} }
func (m *CompleteResponse) String() string { return proto.CompactTextString(m) }
func (*CompleteResponse) ProtoMessage()    {}
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{7}
}

func (m *CompleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteResponse.Unmarshal(m, b)
}
func (m *CompleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteResponse.Marshal(b, m, deterministic)
}
func (m *CompleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteResponse.Merge(m, src)
}
func (m *CompleteResponse) XXX_Size() int {
	return xxx_messageInfo_CompleteResponse.Size(m)
}
func (m *CompleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteResponse proto.InternalMessageInfo

func (m *CompleteResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetLogRequest struct {
	// 作业子任务ID
	SubTaskId            int64    `protobuf:"varint,1,opt,name=sub_task_id,json=subTaskId,proto3" json:"sub_task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogRequest) Reset()         { *m = GetLogRequest{} }
func (m *GetLogRequest) String() string { return proto.CompactTextString(m) }
func (*GetLogRequest) ProtoMessage()    {}
func (*GetLogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{8}
}

func (m *GetLogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogRequest.Unmarshal(m, b)
}
func (m *GetLogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogRequest.Marshal(b, m, deterministic)
}
func (m *GetLogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogRequest.Merge(m, src)
}
func (m *GetLogRequest) XXX_Size() int {
	return xxx_messageInfo_GetLogRequest.Size(m)
}
func (m *GetLogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogRequest proto.InternalMessageInfo

func (m *GetLogRequest) GetSubTaskId() int64 {
	if m != nil {
		return m.SubTaskId
	}
	return 0
}

type GetLogResponse struct {
	// 返回的请求状态
	Status *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// 子任务实例名
	SubTaskLog           string   `protobuf:"bytes,2,opt,name=sub_task_log,json=subTaskLog,proto3" json:"sub_task_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLogResponse) Reset()         { *m = GetLogResponse{} }
func (m *GetLogResponse) String() string { return proto.CompactTextString(m) }
func (*GetLogResponse) ProtoMessage()    {}
func (*GetLogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13c21d1fa7c9a311, []int{9}
}

func (m *GetLogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLogResponse.Unmarshal(m, b)
}
func (m *GetLogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLogResponse.Marshal(b, m, deterministic)
}
func (m *GetLogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLogResponse.Merge(m, src)
}
func (m *GetLogResponse) XXX_Size() int {
	return xxx_messageInfo_GetLogResponse.Size(m)
}
func (m *GetLogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLogResponse proto.InternalMessageInfo

func (m *GetLogResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *GetLogResponse) GetSubTaskLog() string {
	if m != nil {
		return m.SubTaskLog
	}
	return ""
}

func init() {
	proto.RegisterEnum("subtask.ServerTaskType", ServerTaskType_name, ServerTaskType_value)
	proto.RegisterEnum("subtask.SubTaskResult", SubTaskResult_name, SubTaskResult_value)
	proto.RegisterType((*CreateRequest)(nil), "subtask.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "subtask.CreateResponse")
	proto.RegisterType((*CreateServerCompareRequest)(nil), "subtask.CreateServerCompareRequest")
	proto.RegisterType((*CreateServerCompareResponse)(nil), "subtask.CreateServerCompareResponse")
	proto.RegisterType((*CreateServerRequest)(nil), "subtask.CreateServerRequest")
	proto.RegisterType((*CreateServerResponse)(nil), "subtask.CreateServerResponse")
	proto.RegisterType((*CompleteRequest)(nil), "subtask.CompleteRequest")
	proto.RegisterType((*CompleteResponse)(nil), "subtask.CompleteResponse")
	proto.RegisterType((*GetLogRequest)(nil), "subtask.GetLogRequest")
	proto.RegisterType((*GetLogResponse)(nil), "subtask.GetLogResponse")
}

func init() { proto.RegisterFile("subtask/subtask.proto", fileDescriptor_13c21d1fa7c9a311) }

var fileDescriptor_13c21d1fa7c9a311 = []byte{
	// 872 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x5f, 0x6f, 0xdb, 0x54,
	0x14, 0xaf, 0x93, 0x35, 0x69, 0x4e, 0x9a, 0xcc, 0xdc, 0x01, 0x4d, 0xc3, 0xca, 0x22, 0x77, 0x88,
	0x30, 0x31, 0x5b, 0x14, 0x26, 0x1e, 0x78, 0xea, 0xbc, 0x74, 0x8d, 0xc8, 0x4a, 0xe5, 0xa4, 0x42,
	0xe2, 0xc5, 0x73, 0xec, 0x5b, 0xcf, 0xc2, 0xf6, 0x35, 0xbe, 0xd7, 0x5b, 0x27, 0xc4, 0x0b, 0x42,
	0xe2, 0x1d, 0xde, 0xf9, 0x14, 0x7c, 0x13, 0xbe, 0x02, 0x1f, 0x04, 0xdd, 0x3f, 0x4e, 0xe2, 0x2e,
	0x6b, 0x2b, 0x10, 0x2f, 0xb1, 0x7d, 0x7e, 0xbf, 0x7b, 0x7e, 0xe7, 0xfe, 0xce, 0xb9, 0x76, 0xe0,
	0x3d, 0x5a, 0xcc, 0x99, 0x47, 0xbf, 0xb7, 0xd4, 0xd5, 0xcc, 0x72, 0xc2, 0x08, 0x6a, 0xaa, 0xc7,
	0xfe, 0xdd, 0x90, 0x90, 0x30, 0xc6, 0x96, 0x97, 0x45, 0x96, 0x97, 0xa6, 0x84, 0x79, 0x2c, 0x22,
	0x29, 0x95, 0xb4, 0xfe, 0xa7, 0xe2, 0xe2, 0x3f, 0x0c, 0x71, 0xfa, 0x90, 0xbe, 0xf2, 0xc2, 0x10,
	0xe7, 0x16, 0xc9, 0x04, 0x63, 0x0d, 0x5b, 0xf7, 0x49, 0x92, 0x90, 0x94, 0xe7, 0x52, 0x91, 0xdb,
	0x7e, 0x12, 0xcc, 0x2d, 0xfe, 0x23, 0x03, 0xc6, 0x6f, 0x1a, 0x74, 0xec, 0x1c, 0x7b, 0x0c, 0x3b,
	0xf8, 0x87, 0x02, 0x53, 0x86, 0x76, 0xa0, 0xc9, 0x0b, 0x71, 0xa3, 0xa0, 0xa7, 0x0d, 0xb4, 0x61,
	0xdd, 0x69, 0xf0, 0xc7, 0x71, 0x80, 0x9e, 0xc2, 0x1d, 0xbe, 0xd0, 0xa5, 0xd8, 0xcb, 0xfd, 0x17,
	0x6e, 0x2e, 0xf9, 0xbd, 0xda, 0x40, 0x1b, 0xb6, 0x0f, 0x76, 0x4c, 0x91, 0xd4, 0x7e, 0x41, 0x08,
	0xc5, 0xc7, 0x84, 0x32, 0x95, 0xce, 0x79, 0x87, 0xc7, 0xa7, 0x62, 0x49, 0xa9, 0x70, 0x0f, 0xda,
	0x0c, 0x27, 0x59, 0xec, 0x31, 0xcc, 0x55, 0xea, 0x03, 0x6d, 0xb8, 0xe9, 0x40, 0x19, 0x1a, 0x07,
	0xc6, 0x73, 0xe8, 0x96, 0x35, 0xd1, 0x8c, 0xa4, 0x14, 0xa3, 0x0f, 0xa1, 0x4d, 0x8b, 0xb9, 0xbb,
	0x2c, 0xac, 0x3e, 0xac, 0x3b, 0x2d, 0x5a, 0xcc, 0x67, 0xb2, 0x36, 0x13, 0x1a, 0x94, 0x79, 0xac,
	0xa0, 0xaa, 0x9c, 0xf7, 0x4d, 0xb9, 0x75, 0xb3, 0xcc, 0x30, 0x15, 0xa8, 0xa3, 0x58, 0xc6, 0xaf,
	0x1a, 0xf4, 0xa5, 0xc4, 0x14, 0xe7, 0x2f, 0x71, 0x6e, 0x93, 0x24, 0xf3, 0xf2, 0xeb, 0x3d, 0x38,
	0xbd, 0xca, 0x83, 0xc1, 0xaa, 0x07, 0xeb, 0xf2, 0xae, 0x31, 0xc3, 0x48, 0xe0, 0x83, 0xb5, 0x85,
	0xbc, 0x6d, 0xe3, 0xda, 0x7f, 0xdb, 0xf8, 0x9f, 0x35, 0xb8, 0xb3, 0xaa, 0x77, 0xed, 0x8e, 0xbf,
	0x80, 0x96, 0x00, 0xd8, 0xeb, 0x0c, 0x0b, 0x8d, 0xee, 0xc1, 0x8e, 0x59, 0xce, 0xae, 0xcc, 0xc1,
	0x4b, 0x99, 0xbd, 0xce, 0xb0, 0xb3, 0xc5, 0xd4, 0x1d, 0xfa, 0x12, 0xda, 0x19, 0x79, 0x85, 0x73,
	0x97, 0xcb, 0x62, 0xd1, 0xe2, 0x2e, 0xaf, 0x8d, 0xfb, 0x23, 0x17, 0x9d, 0x72, 0x98, 0x17, 0x87,
	0x1d, 0xc8, 0x16, 0xf7, 0x68, 0xbc, 0xde, 0xe0, 0x5b, 0x62, 0x73, 0xbb, 0x6f, 0x1a, 0x7c, 0xc5,
	0x98, 0xdd, 0x87, 0x6e, 0x94, 0x78, 0x21, 0x76, 0xcf, 0xa3, 0x18, 0xbb, 0x45, 0x1e, 0xf7, 0x36,
	0x07, 0xda, 0xb0, 0xe5, 0x6c, 0x8b, 0xe8, 0x51, 0x14, 0xe3, 0xb3, 0x3c, 0xbe, 0xc4, 0x4a, 0x82,
	0x47, 0xbd, 0xc6, 0x25, 0xd6, 0xb3, 0xe0, 0x91, 0x71, 0x0e, 0xef, 0x56, 0x5d, 0xfb, 0x9f, 0xda,
	0xf3, 0x4b, 0x0d, 0x6e, 0xf3, 0x11, 0x88, 0xf1, 0xf2, 0x40, 0x5e, 0xa7, 0xb1, 0x07, 0x40, 0x99,
	0x97, 0x33, 0x97, 0x45, 0x89, 0x6c, 0x51, 0xcb, 0x69, 0x89, 0xc8, 0x2c, 0x4a, 0x30, 0xda, 0x85,
	0x2d, 0x9c, 0x06, 0x12, 0xac, 0x0b, 0xb0, 0x89, 0xd3, 0x40, 0x40, 0x26, 0x34, 0x72, 0x4c, 0x8b,
	0x58, 0xfa, 0xcb, 0x1b, 0xb4, 0x68, 0xac, 0xcc, 0xee, 0x08, 0xd4, 0x51, 0x2c, 0xb4, 0x0f, 0x1d,
	0x7c, 0x81, 0xfd, 0x82, 0x61, 0xd7, 0x27, 0x45, 0xca, 0x84, 0xa1, 0x9b, 0xce, 0xb6, 0x0a, 0xda,
	0x3c, 0xc6, 0xcb, 0x39, 0xf7, 0xa2, 0x58, 0x31, 0x1a, 0x82, 0xd1, 0xe2, 0x11, 0x09, 0xef, 0x43,
	0x87, 0x16, 0xbe, 0x8f, 0x29, 0x55, 0x8c, 0xa6, 0xcc, 0xa1, 0x82, 0x82, 0x64, 0x3c, 0x06, 0x7d,
	0xe9, 0x82, 0xb2, 0x7a, 0x69, 0xa5, 0x76, 0x23, 0x2b, 0x2d, 0xe8, 0x3c, 0xc5, 0x6c, 0x42, 0xc2,
	0x1b, 0xfa, 0x68, 0xcc, 0xa1, 0x5b, 0x2e, 0xf8, 0x77, 0x92, 0x68, 0x00, 0xdb, 0x0b, 0x85, 0x98,
	0x84, 0xaa, 0x17, 0xa0, 0x24, 0x26, 0x24, 0x7c, 0x70, 0x02, 0xdd, 0xea, 0x99, 0x41, 0x1d, 0x68,
	0x9d, 0x9d, 0x3c, 0x19, 0x1d, 0x8d, 0x4f, 0x46, 0x4f, 0xf4, 0x0d, 0xd4, 0x82, 0x4d, 0xfb, 0x78,
	0x64, 0x7f, 0xad, 0x6b, 0xfc, 0xf6, 0xf4, 0x9b, 0x6f, 0x47, 0x8e, 0x5e, 0x43, 0x00, 0x0d, 0xdb,
	0x19, 0x1d, 0xce, 0x46, 0x7a, 0x1d, 0xb5, 0xa1, 0x39, 0x3e, 0x99, 0xce, 0x0e, 0x27, 0x13, 0xfd,
	0xd6, 0x83, 0x4f, 0xa0, 0x53, 0x69, 0x15, 0x47, 0x8f, 0x0e, 0xc7, 0x93, 0x33, 0x67, 0xa4, 0x6f,
	0xf0, 0x87, 0xe9, 0x99, 0x6d, 0x8f, 0xa6, 0x53, 0x5d, 0x3b, 0xf8, 0xa3, 0x0e, 0x4d, 0xc5, 0x45,
	0x5f, 0x41, 0x43, 0x8e, 0x33, 0x5a, 0xb6, 0xbc, 0xf2, 0x15, 0xe8, 0xef, 0xbc, 0x11, 0x97, 0x3b,
	0x36, 0x36, 0xd0, 0x21, 0x6c, 0x95, 0xcd, 0x41, 0xbd, 0x25, 0xad, 0x3a, 0xb5, 0xfd, 0xdd, 0x35,
	0xc8, 0x22, 0xc5, 0x33, 0xd8, 0x5e, 0x3d, 0x4e, 0xe8, 0xee, 0x25, 0xb5, 0xca, 0xd9, 0xee, 0xef,
	0xbd, 0x05, 0x5d, 0xa4, 0x9b, 0x57, 0xdf, 0x69, 0xea, 0x1d, 0x8a, 0xf6, 0xd7, 0xae, 0xab, 0xbe,
	0x92, 0xfb, 0xf7, 0xaf, 0x26, 0x2d, 0x34, 0x9e, 0x43, 0x43, 0x4e, 0xc7, 0x8a, 0x65, 0x95, 0xf9,
	0x5a, 0xb1, 0xac, 0x3a, 0x46, 0xc6, 0x47, 0x3f, 0xff, 0xf5, 0xf7, 0xef, 0xb5, 0x7b, 0x68, 0xcf,
	0x7a, 0xf9, 0x99, 0x25, 0xbe, 0xfd, 0xa1, 0x20, 0x58, 0x3f, 0xae, 0xcc, 0xe3, 0x4f, 0x8f, 0x8f,
	0x61, 0x8f, 0x91, 0xcc, 0x3c, 0x27, 0xa1, 0x1f, 0xa4, 0xa6, 0x77, 0x81, 0xe5, 0x27, 0x9a, 0x96,
	0x69, 0xbf, 0xfb, 0x38, 0x8c, 0x58, 0x09, 0x33, 0x92, 0x59, 0xde, 0x05, 0xb6, 0x24, 0xc5, 0x0a,
	0x09, 0x29, 0x58, 0xf9, 0x97, 0x62, 0xde, 0x10, 0xd1, 0xcf, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x91, 0x19, 0xfe, 0xad, 0x6c, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SubTaskClient is the client API for SubTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubTaskClient interface {
	// 创建作业子任务
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// 完成作业子任务
	Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error)
	// 创建裸金属子任务
	CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error)
	// 交维表导入后巡检子任务
	CreateServerCompare(ctx context.Context, in *CreateServerCompareRequest, opts ...grpc.CallOption) (*CreateServerCompareResponse, error)
	// 获取作业任务SubTask具体日志
	GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogResponse, error)
}

type subTaskClient struct {
	cc *grpc.ClientConn
}

func NewSubTaskClient(cc *grpc.ClientConn) SubTaskClient {
	return &subTaskClient{cc}
}

func (c *subTaskClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/subtask.SubTask/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subTaskClient) Complete(ctx context.Context, in *CompleteRequest, opts ...grpc.CallOption) (*CompleteResponse, error) {
	out := new(CompleteResponse)
	err := c.cc.Invoke(ctx, "/subtask.SubTask/Complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subTaskClient) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...grpc.CallOption) (*CreateServerResponse, error) {
	out := new(CreateServerResponse)
	err := c.cc.Invoke(ctx, "/subtask.SubTask/CreateServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subTaskClient) CreateServerCompare(ctx context.Context, in *CreateServerCompareRequest, opts ...grpc.CallOption) (*CreateServerCompareResponse, error) {
	out := new(CreateServerCompareResponse)
	err := c.cc.Invoke(ctx, "/subtask.SubTask/CreateServerCompare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subTaskClient) GetLog(ctx context.Context, in *GetLogRequest, opts ...grpc.CallOption) (*GetLogResponse, error) {
	out := new(GetLogResponse)
	err := c.cc.Invoke(ctx, "/subtask.SubTask/GetLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubTaskServer is the server API for SubTask service.
type SubTaskServer interface {
	// 创建作业子任务
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// 完成作业子任务
	Complete(context.Context, *CompleteRequest) (*CompleteResponse, error)
	// 创建裸金属子任务
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerResponse, error)
	// 交维表导入后巡检子任务
	CreateServerCompare(context.Context, *CreateServerCompareRequest) (*CreateServerCompareResponse, error)
	// 获取作业任务SubTask具体日志
	GetLog(context.Context, *GetLogRequest) (*GetLogResponse, error)
}

// UnimplementedSubTaskServer can be embedded to have forward compatible implementations.
type UnimplementedSubTaskServer struct {
}

func (*UnimplementedSubTaskServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSubTaskServer) Complete(ctx context.Context, req *CompleteRequest) (*CompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (*UnimplementedSubTaskServer) CreateServer(ctx context.Context, req *CreateServerRequest) (*CreateServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServer not implemented")
}
func (*UnimplementedSubTaskServer) CreateServerCompare(ctx context.Context, req *CreateServerCompareRequest) (*CreateServerCompareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServerCompare not implemented")
}
func (*UnimplementedSubTaskServer) GetLog(ctx context.Context, req *GetLogRequest) (*GetLogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLog not implemented")
}

func RegisterSubTaskServer(s *grpc.Server, srv SubTaskServer) {
	s.RegisterService(&_SubTask_serviceDesc, srv)
}

func _SubTask_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubTaskServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtask.SubTask/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubTaskServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubTask_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubTaskServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtask.SubTask/Complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubTaskServer).Complete(ctx, req.(*CompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubTask_CreateServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubTaskServer).CreateServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtask.SubTask/CreateServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubTaskServer).CreateServer(ctx, req.(*CreateServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubTask_CreateServerCompare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServerCompareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubTaskServer).CreateServerCompare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtask.SubTask/CreateServerCompare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubTaskServer).CreateServerCompare(ctx, req.(*CreateServerCompareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubTask_GetLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubTaskServer).GetLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtask.SubTask/GetLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubTaskServer).GetLog(ctx, req.(*GetLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubTask_serviceDesc = grpc.ServiceDesc{
	ServiceName: "subtask.SubTask",
	HandlerType: (*SubTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SubTask_Create_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _SubTask_Complete_Handler,
		},
		{
			MethodName: "CreateServer",
			Handler:    _SubTask_CreateServer_Handler,
		},
		{
			MethodName: "CreateServerCompare",
			Handler:    _SubTask_CreateServerCompare_Handler,
		},
		{
			MethodName: "GetLog",
			Handler:    _SubTask_GetLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subtask/subtask.proto",
}
