// Code generated by protoc-gen-go. DO NOT EDIT.
// source: image/common.proto

package image

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求返回状态码
type StatusCode int32

const (
	// 成功
	StatusCode_SUCCESS StatusCode = 0
	// 参数错误
	StatusCode_INVALID_ARGUMENT StatusCode = 400
	// 访问拒绝
	StatusCode_ACCESS_DENIED StatusCode = 403
	// 内部错误
	StatusCode_INTERNAL_ERROR StatusCode = 500
)

var StatusCode_name = map[int32]string{
	0:   "SUCCESS",
	400: "INVALID_ARGUMENT",
	403: "ACCESS_DENIED",
	500: "INTERNAL_ERROR",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":          0,
	"INVALID_ARGUMENT": 400,
	"ACCESS_DENIED":    403,
	"INTERNAL_ERROR":   500,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bd77daef00196b62, []int{0}
}

// 分页信息(每个服务通用的控制信息，当客户端发起请求时，信息填写如下)
type Paging struct {
	// 总页数
	TotalPage int32 `protobuf:"varint,1,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	// 当前页数
	Page int32 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	// 每页显示的记录条数
	PerPage int32 `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	// 总记录数
	TotalRecord          int32    `protobuf:"varint,4,opt,name=total_record,json=totalRecord,proto3" json:"total_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd77daef00196b62, []int{0}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *Paging) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Paging) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *Paging) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

// 时间范围信息(用于指定时间范围。如按受理开始时间、受理结束时间查询订单列表。按某个具体时间查询，不使用此对象。)
type TimeScope struct {
	// 起始时间
	BeginDate *timestamp.Timestamp `protobuf:"bytes,1,opt,name=begin_date,json=beginDate,proto3" json:"begin_date,omitempty"`
	// 结束时间
	EndDate              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TimeScope) Reset()         { *m = TimeScope{} }
func (m *TimeScope) String() string { return proto.CompactTextString(m) }
func (*TimeScope) ProtoMessage()    {}
func (*TimeScope) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd77daef00196b62, []int{1}
}

func (m *TimeScope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeScope.Unmarshal(m, b)
}
func (m *TimeScope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeScope.Marshal(b, m, deterministic)
}
func (m *TimeScope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeScope.Merge(m, src)
}
func (m *TimeScope) XXX_Size() int {
	return xxx_messageInfo_TimeScope.Size(m)
}
func (m *TimeScope) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeScope.DiscardUnknown(m)
}

var xxx_messageInfo_TimeScope proto.InternalMessageInfo

func (m *TimeScope) GetBeginDate() *timestamp.Timestamp {
	if m != nil {
		return m.BeginDate
	}
	return nil
}

func (m *TimeScope) GetEndDate() *timestamp.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

// 请求返回状态
type ResponseStatus struct {
	// 状态码
	Code StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=image.StatusCode" json:"code,omitempty"`
	// 信息
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd77daef00196b62, []int{2}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *ResponseStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("image.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Paging)(nil), "image.Paging")
	proto.RegisterType((*TimeScope)(nil), "image.TimeScope")
	proto.RegisterType((*ResponseStatus)(nil), "image.ResponseStatus")
}

func init() { proto.RegisterFile("image/common.proto", fileDescriptor_bd77daef00196b62) }

var fileDescriptor_bd77daef00196b62 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x51, 0x6b, 0x13, 0x41,
	0x14, 0x85, 0x4d, 0x93, 0x36, 0xcd, 0x8d, 0x0d, 0x71, 0x44, 0x88, 0x05, 0x51, 0x03, 0x05, 0xe9,
	0xc3, 0x2c, 0x54, 0x7c, 0xf0, 0x31, 0x4d, 0x16, 0x09, 0xd4, 0x35, 0xce, 0xa6, 0x82, 0xbe, 0x2c,
	0x93, 0xd9, 0x9b, 0x61, 0xa0, 0xb3, 0x77, 0x98, 0x9d, 0x40, 0x7d, 0xf0, 0x3f, 0x08, 0xfe, 0x55,
	0x7f, 0x80, 0x74, 0xc6, 0xc5, 0x47, 0xdf, 0xee, 0x7e, 0xe7, 0x9c, 0xbd, 0x87, 0xcb, 0x00, 0x33,
	0x56, 0x6a, 0xcc, 0x14, 0x59, 0x4b, 0x0d, 0x77, 0x9e, 0x02, 0xb1, 0xe3, 0xc8, 0xce, 0x5f, 0x6a,
	0x22, 0x7d, 0x87, 0x59, 0x84, 0xbb, 0xc3, 0x3e, 0x0b, 0xc6, 0x62, 0x1b, 0xa4, 0x75, 0xc9, 0x37,
	0xff, 0x0e, 0x27, 0x1b, 0xa9, 0x4d, 0xa3, 0xd9, 0x0b, 0x80, 0x40, 0x41, 0xde, 0x55, 0x4e, 0x6a,
	0x9c, 0xf5, 0x5e, 0xf5, 0xde, 0x1c, 0x8b, 0x51, 0x24, 0x1b, 0xa9, 0x91, 0x31, 0x18, 0x44, 0xe1,
	0x28, 0x0a, 0x71, 0x66, 0xcf, 0xe1, 0xd4, 0xa1, 0x4f, 0x81, 0x7e, 0xe4, 0x43, 0x87, 0x3e, 0xda,
	0x5f, 0xc3, 0xe3, 0xf4, 0x37, 0x8f, 0x8a, 0x7c, 0x3d, 0x1b, 0x44, 0x79, 0x1c, 0x99, 0x88, 0x68,
	0xfe, 0x03, 0x46, 0x5b, 0x63, 0xb1, 0x54, 0xe4, 0x90, 0xbd, 0x07, 0xd8, 0xa1, 0x36, 0x4d, 0x55,
	0xcb, 0x90, 0xb6, 0x8f, 0xaf, 0xce, 0x79, 0x6a, 0xcf, 0xbb, 0xf6, 0x7c, 0xdb, 0xb5, 0x17, 0xa3,
	0xe8, 0x5e, 0xc9, 0x80, 0xec, 0x1d, 0x9c, 0x62, 0x53, 0xa7, 0xe0, 0xd1, 0x7f, 0x83, 0x43, 0x6c,
	0xea, 0x87, 0xd8, 0xfc, 0x33, 0x4c, 0x04, 0xb6, 0x8e, 0x9a, 0x16, 0xcb, 0x20, 0xc3, 0xa1, 0x65,
	0x17, 0x30, 0x50, 0x54, 0xa7, 0xed, 0x93, 0xab, 0x27, 0x3c, 0x9e, 0x90, 0x27, 0x71, 0x49, 0x35,
	0x8a, 0x28, 0xb3, 0x19, 0x0c, 0x2d, 0xb6, 0x6d, 0x77, 0x8c, 0x91, 0xe8, 0x3e, 0x2f, 0xbf, 0x02,
	0xfc, 0x73, 0xb3, 0x31, 0x0c, 0xcb, 0xdb, 0xe5, 0x32, 0x2f, 0xcb, 0xe9, 0x23, 0xf6, 0x0c, 0xa6,
	0xeb, 0xe2, 0xcb, 0xe2, 0x66, 0xbd, 0xaa, 0x16, 0xe2, 0xc3, 0xed, 0xc7, 0xbc, 0xd8, 0x4e, 0x7f,
	0xf6, 0x19, 0x83, 0xb3, 0x45, 0xb4, 0x54, 0xab, 0xbc, 0x58, 0xe7, 0xab, 0xe9, 0xaf, 0x3e, 0x7b,
	0x0a, 0x93, 0x75, 0xb1, 0xcd, 0x45, 0xb1, 0xb8, 0xa9, 0x72, 0x21, 0x3e, 0x89, 0xe9, 0xef, 0xfe,
	0x75, 0x0d, 0x97, 0x8a, 0x2c, 0xdf, 0xef, 0x55, 0xcb, 0xef, 0xad, 0xaf, 0x15, 0x37, 0x9e, 0x1a,
	0xa3, 0xb8, 0x35, 0xde, 0x93, 0xe7, 0xda, 0x3b, 0x95, 0x0a, 0x2f, 0xc9, 0x5e, 0x9f, 0x75, 0xd3,
	0xe6, 0xe1, 0x00, 0x9b, 0xde, 0xb7, 0x0b, 0x6d, 0x02, 0xdf, 0x93, 0x56, 0x75, 0xc3, 0x03, 0xb9,
	0x4c, 0xde, 0xff, 0x7d, 0x13, 0x6d, 0xa6, 0x89, 0x0e, 0x21, 0x8b, 0x81, 0xdd, 0x49, 0x64, 0x6f,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x8c, 0x36, 0x82, 0x52, 0x02, 0x00, 0x00,
}
