// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playbook/playbook.proto

package playbook

import (
	context "context"
	fmt "fmt"
	common "git.fogcdn.top/axe/protos/goout/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UrlType int32

const (
	UrlType_UNDEFINED UrlType = 0
	UrlType_FILE      UrlType = 1
	UrlType_GIT       UrlType = 2
)

var UrlType_name = map[int32]string{
	0: "UNDEFINED",
	1: "FILE",
	2: "GIT",
}

var UrlType_value = map[string]int32{
	"UNDEFINED": 0,
	"FILE":      1,
	"GIT":       2,
}

func (x UrlType) String() string {
	return proto.EnumName(UrlType_name, int32(x))
}

func (UrlType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{0}
}

// 项目实例
type ProjectObject struct {
	PlaybookId           int32    `protobuf:"varint,1,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	UrlType              UrlType  `protobuf:"varint,5,opt,name=url_type,json=urlType,proto3,enum=proto.UrlType" json:"url_type,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Entrypoint           []string `protobuf:"bytes,7,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Created              string   `protobuf:"bytes,10,opt,name=created,proto3" json:"created,omitempty"`
	Updated              string   `protobuf:"bytes,11,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectObject) Reset()         { *m = ProjectObject{} }
func (m *ProjectObject) String() string { return proto.CompactTextString(m) }
func (*ProjectObject) ProtoMessage()    {}
func (*ProjectObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{0}
}

func (m *ProjectObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectObject.Unmarshal(m, b)
}
func (m *ProjectObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectObject.Marshal(b, m, deterministic)
}
func (m *ProjectObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectObject.Merge(m, src)
}
func (m *ProjectObject) XXX_Size() int {
	return xxx_messageInfo_ProjectObject.Size(m)
}
func (m *ProjectObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectObject.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectObject proto.InternalMessageInfo

func (m *ProjectObject) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

func (m *ProjectObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProjectObject) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ProjectObject) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProjectObject) GetUrlType() UrlType {
	if m != nil {
		return m.UrlType
	}
	return UrlType_UNDEFINED
}

func (m *ProjectObject) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ProjectObject) GetEntrypoint() []string {
	if m != nil {
		return m.Entrypoint
	}
	return nil
}

func (m *ProjectObject) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ProjectObject) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

// 创建项目请求内容体
type CreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	UrlType              UrlType  `protobuf:"varint,4,opt,name=url_type,json=urlType,proto3,enum=proto.UrlType" json:"url_type,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Entrypoint           []string `protobuf:"bytes,6,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateRequest) GetUrlType() UrlType {
	if m != nil {
		return m.UrlType
	}
	return UrlType_UNDEFINED
}

func (m *CreateRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CreateRequest) GetEntrypoint() []string {
	if m != nil {
		return m.Entrypoint
	}
	return nil
}

// 创建项目请求返回
type CreateResponse struct {
	PlaybookId           int32                  `protobuf:"varint,1,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	Created              string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Status               *common.ResponseStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

func (m *CreateResponse) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *CreateResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 根据项目ID获取记录
type GetRequest struct {
	PlaybookId           int32    `protobuf:"varint,1,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

// 获取项目请求返回
type GetResponse struct {
	Project              *ProjectObject         `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Status               *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetProject() *ProjectObject {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *GetResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 筛选项目请求
type FilterRequest struct {
	Paging               *common.Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Keyword              string         `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *FilterRequest) Reset()         { *m = FilterRequest{} }
func (m *FilterRequest) String() string { return proto.CompactTextString(m) }
func (*FilterRequest) ProtoMessage()    {}
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{5}
}

func (m *FilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRequest.Unmarshal(m, b)
}
func (m *FilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRequest.Marshal(b, m, deterministic)
}
func (m *FilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRequest.Merge(m, src)
}
func (m *FilterRequest) XXX_Size() int {
	return xxx_messageInfo_FilterRequest.Size(m)
}
func (m *FilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRequest proto.InternalMessageInfo

func (m *FilterRequest) GetPaging() *common.Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *FilterRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

// 筛选项目请求返回
type FilterResponse struct {
	Projects             []*ProjectObject       `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	Paging               *common.Paging         `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	Status               *common.ResponseStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *FilterResponse) Reset()         { *m = FilterResponse{} }
func (m *FilterResponse) String() string { return proto.CompactTextString(m) }
func (*FilterResponse) ProtoMessage()    {}
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{6}
}

func (m *FilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterResponse.Unmarshal(m, b)
}
func (m *FilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterResponse.Marshal(b, m, deterministic)
}
func (m *FilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterResponse.Merge(m, src)
}
func (m *FilterResponse) XXX_Size() int {
	return xxx_messageInfo_FilterResponse.Size(m)
}
func (m *FilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterResponse proto.InternalMessageInfo

func (m *FilterResponse) GetProjects() []*ProjectObject {
	if m != nil {
		return m.Projects
	}
	return nil
}

func (m *FilterResponse) GetPaging() *common.Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *FilterResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 更新项目请求内容体
type UpdateRequest struct {
	PlaybookId           int32    `protobuf:"varint,1,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Entrypoint           []string `protobuf:"bytes,7,rep,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{7}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *UpdateRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *UpdateRequest) GetEntrypoint() []string {
	if m != nil {
		return m.Entrypoint
	}
	return nil
}

// 更新项目请求返回
type UpdateResponse struct {
	Updated              string                 `protobuf:"bytes,1,opt,name=updated,proto3" json:"updated,omitempty"`
	Status               *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{8}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetUpdated() string {
	if m != nil {
		return m.Updated
	}
	return ""
}

func (m *UpdateResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 根据ID删除记录
type DeleteRequest struct {
	PlaybookId           int32    `protobuf:"varint,1,opt,name=playbook_id,json=playbookId,proto3" json:"playbook_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{9}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetPlaybookId() int32 {
	if m != nil {
		return m.PlaybookId
	}
	return 0
}

// 删除记录请求返回
type DeleteResponse struct {
	Status               *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8024ac646511ddb, []int{10}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.UrlType", UrlType_name, UrlType_value)
	proto.RegisterType((*ProjectObject)(nil), "proto.ProjectObject")
	proto.RegisterType((*CreateRequest)(nil), "proto.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "proto.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "proto.GetResponse")
	proto.RegisterType((*FilterRequest)(nil), "proto.FilterRequest")
	proto.RegisterType((*FilterResponse)(nil), "proto.FilterResponse")
	proto.RegisterType((*UpdateRequest)(nil), "proto.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "proto.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "proto.DeleteResponse")
}

func init() { proto.RegisterFile("playbook/playbook.proto", fileDescriptor_f8024ac646511ddb) }

var fileDescriptor_f8024ac646511ddb = []byte{
	// 809 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x67, 0xed, 0xc4, 0x49, 0x27, 0x17, 0x2b, 0xb7, 0x3a, 0x38, 0x2b, 0x3a, 0x71, 0x91, 0x25,
	0x50, 0x08, 0xd4, 0x4e, 0xc3, 0xdb, 0x3d, 0x11, 0x68, 0x5a, 0x45, 0xa0, 0x12, 0x7c, 0xad, 0x04,
	0x15, 0xd2, 0xc9, 0x4d, 0xf6, 0x2c, 0xdf, 0x39, 0x5e, 0x63, 0xaf, 0xef, 0x88, 0x2a, 0x5e, 0x78,
	0xe1, 0x91, 0x7f, 0x6f, 0x7c, 0x0a, 0x54, 0x78, 0x41, 0x20, 0xf1, 0x21, 0xf8, 0x0a, 0x54, 0xf0,
	0x31, 0x90, 0xd7, 0xbb, 0xc6, 0x6e, 0x69, 0x9a, 0xa2, 0x7b, 0x69, 0x76, 0x67, 0x66, 0x7f, 0xf3,
	0x9b, 0x99, 0xdf, 0xd4, 0x70, 0x37, 0x0a, 0xdc, 0xd5, 0x09, 0xa5, 0x4f, 0x6d, 0x79, 0xb0, 0xa2,
	0x98, 0x32, 0x8a, 0xeb, 0xfc, 0xa7, 0xdb, 0x99, 0xd3, 0xe5, 0x92, 0x86, 0xb6, 0x1b, 0xf9, 0xb9,
	0xa3, 0x7b, 0xcf, 0xa3, 0xd4, 0x0b, 0x48, 0x66, 0xb1, 0xdd, 0x30, 0xa4, 0xcc, 0x65, 0x3e, 0x0d,
	0x13, 0xe1, 0x7d, 0x8b, 0xff, 0xcc, 0xb7, 0x3d, 0x12, 0x6e, 0x27, 0xcf, 0x5d, 0xcf, 0x23, 0xb1,
	0x4d, 0x23, 0x1e, 0x71, 0x39, 0xda, 0xfc, 0x56, 0x81, 0xf6, 0x2c, 0xa6, 0x4f, 0xc8, 0x9c, 0x7d,
	0x78, 0x92, 0xfd, 0xc5, 0xf7, 0xa1, 0x25, 0x89, 0x3c, 0xf2, 0x17, 0x06, 0xea, 0xa1, 0x7e, 0xdd,
	0x01, 0x69, 0x9a, 0x2e, 0x30, 0x86, 0x5a, 0xe8, 0x2e, 0x89, 0xa1, 0xf4, 0x50, 0x7f, 0xcb, 0xe1,
	0x67, 0xdc, 0x83, 0xd6, 0x82, 0x24, 0xf3, 0xd8, 0xe7, 0x89, 0x0c, 0x95, 0xbb, 0xca, 0x26, 0xdc,
	0x01, 0x35, 0x8d, 0x03, 0xa3, 0xc6, 0x3d, 0xd9, 0x11, 0xbf, 0x01, 0xcd, 0x34, 0x0e, 0x1e, 0xb1,
	0x55, 0x44, 0x8c, 0x7a, 0x0f, 0xf5, 0xf5, 0x91, 0x9e, 0x93, 0xb2, 0x8e, 0xe2, 0xe0, 0x70, 0x15,
	0x11, 0xa7, 0x91, 0xe6, 0x07, 0x6c, 0x40, 0xe3, 0x19, 0x89, 0x93, 0x0c, 0x5a, 0xe3, 0x00, 0xf2,
	0x8a, 0x5f, 0x05, 0x20, 0x21, 0x8b, 0x57, 0x11, 0xf5, 0x43, 0x66, 0x34, 0x7a, 0x6a, 0x7f, 0xcb,
	0x29, 0x59, 0xb2, 0x97, 0xf3, 0x98, 0xb8, 0x8c, 0x2c, 0x0c, 0xc8, 0x5f, 0x8a, 0x6b, 0xe6, 0x49,
	0xa3, 0x05, 0xf7, 0xb4, 0x72, 0x8f, 0xb8, 0x9a, 0xbf, 0x21, 0x68, 0xbf, 0xc7, 0xa3, 0x1c, 0xf2,
	0x59, 0x4a, 0x12, 0x56, 0x94, 0x8c, 0xae, 0x2e, 0x59, 0xb9, 0xb2, 0x64, 0xf5, 0xbf, 0x4b, 0xae,
	0x6d, 0x5c, 0x72, 0x7d, 0x5d, 0xc9, 0xda, 0xc5, 0x92, 0xcd, 0x53, 0xd0, 0x25, 0xfb, 0x24, 0xa2,
	0x61, 0x42, 0xae, 0x1f, 0x69, 0xa9, 0x4b, 0x4a, 0xb5, 0x4b, 0x16, 0x68, 0x09, 0x73, 0x59, 0x9a,
	0xf0, 0x32, 0x5a, 0xa3, 0x57, 0xac, 0x5c, 0x8e, 0x96, 0x04, 0x7f, 0xc8, 0xbd, 0x8e, 0x88, 0x32,
	0xb7, 0x01, 0xf6, 0x09, 0x93, 0x7d, 0xbb, 0x2e, 0xb1, 0xb9, 0x84, 0x16, 0x0f, 0x17, 0x44, 0x2d,
	0x68, 0x44, 0xb9, 0x18, 0x79, 0x6c, 0x6b, 0x74, 0x47, 0xb4, 0xa7, 0x22, 0x51, 0x47, 0x06, 0x95,
	0xd8, 0x29, 0x1b, 0xb1, 0xfb, 0x08, 0xda, 0x7b, 0x7e, 0xc0, 0x48, 0x2c, 0x09, 0xbe, 0x0e, 0x5a,
	0xe4, 0x7a, 0x7e, 0xe8, 0x89, 0x7c, 0xba, 0x04, 0x98, 0x71, 0xab, 0x23, 0xbc, 0x59, 0x83, 0x9e,
	0x92, 0xd5, 0x73, 0x1a, 0x17, 0x0d, 0x12, 0x57, 0xf3, 0x07, 0x04, 0xba, 0xc4, 0x14, 0x55, 0x0c,
	0xa1, 0x29, 0x08, 0x26, 0x06, 0xea, 0xa9, 0x57, 0x96, 0x51, 0x44, 0x95, 0x68, 0x28, 0x6b, 0x69,
	0xdc, 0x74, 0x1a, 0x67, 0x08, 0xda, 0x47, 0x5c, 0xd5, 0x9b, 0x4e, 0xe4, 0x85, 0x6d, 0xf7, 0xff,
	0x5e, 0x59, 0xf3, 0x18, 0x74, 0xc9, 0x59, 0x34, 0xb4, 0xb4, 0xaa, 0xa8, 0xb2, 0xaa, 0x37, 0x16,
	0xc0, 0x10, 0xda, 0xbb, 0x24, 0x20, 0x9b, 0xf7, 0xc3, 0x7c, 0x07, 0x74, 0xf9, 0xa2, 0x10, 0xa9,
	0xcc, 0x89, 0x36, 0xc9, 0x39, 0x78, 0x13, 0x1a, 0x62, 0xbb, 0x71, 0x1b, 0xb6, 0x8e, 0x0e, 0x76,
	0x27, 0x7b, 0xd3, 0x83, 0xc9, 0x6e, 0xe7, 0x25, 0xdc, 0x84, 0xda, 0xde, 0xf4, 0x83, 0x49, 0x07,
	0xe1, 0x06, 0xa8, 0xfb, 0xd3, 0xc3, 0x8e, 0x32, 0x3a, 0x53, 0xa1, 0x39, 0x13, 0xd9, 0xf1, 0x01,
	0x68, 0xf9, 0x26, 0x63, 0x29, 0xa0, 0xca, 0xbf, 0xa5, 0xee, 0xcb, 0x17, 0xac, 0x79, 0x7a, 0xf3,
	0xee, 0x97, 0x7f, 0xfc, 0xf9, 0xbd, 0x72, 0xdb, 0xbc, 0x65, 0x3f, 0xdb, 0x29, 0x3e, 0x2a, 0x0f,
	0xd0, 0x00, 0xbf, 0x0f, 0x5a, 0x2e, 0xd5, 0x02, 0xaf, 0xb2, 0x0d, 0x05, 0x5e, 0x55, 0xcf, 0xe6,
	0x1d, 0x8e, 0xa7, 0xe3, 0x0a, 0x1e, 0x9e, 0x81, 0xba, 0x4f, 0x18, 0xbe, 0x2d, 0xde, 0xfc, 0xbb,
	0xf5, 0x5d, 0x5c, 0x36, 0x09, 0x0c, 0x93, 0x63, 0xdc, 0xc3, 0xdd, 0x32, 0x86, 0x7d, 0x5a, 0xea,
	0xfd, 0x17, 0xf8, 0x53, 0xd0, 0xf2, 0xc1, 0x17, 0xf4, 0x2a, 0xda, 0x2d, 0xe8, 0x55, 0xd5, 0x61,
	0xbe, 0xc6, 0xa1, 0xef, 0x77, 0xd7, 0x40, 0x67, 0xc5, 0x7f, 0x02, 0x5a, 0x3e, 0xc8, 0x02, 0xbd,
	0xa2, 0x84, 0x02, 0xbd, 0x3a, 0x6d, 0x49, 0x7c, 0xb0, 0x06, 0xfd, 0xdd, 0xaf, 0xd0, 0x77, 0xe3,
	0x63, 0xbc, 0x03, 0xb7, 0xc6, 0x1f, 0x4f, 0xfe, 0xfe, 0xfd, 0x9b, 0xbf, 0x7e, 0xfd, 0x79, 0x3c,
	0x9b, 0xe2, 0x6e, 0x71, 0x3b, 0xff, 0xe5, 0xa7, 0xf3, 0xaf, 0x7f, 0x74, 0x26, 0x0f, 0x0f, 0x1f,
	0xa7, 0x41, 0x6f, 0x3c, 0x9b, 0x8e, 0xea, 0x3b, 0xd6, 0xd0, 0x1a, 0x0e, 0x10, 0x1a, 0x75, 0xdc,
	0x28, 0x0a, 0xfc, 0x39, 0xff, 0x28, 0xdb, 0x4f, 0x12, 0x1a, 0x3e, 0xb8, 0x64, 0x39, 0xee, 0x7b,
	0x3e, 0xb3, 0x1e, 0x53, 0x6f, 0xbe, 0x08, 0x2d, 0x46, 0x23, 0xdb, 0xfd, 0x9c, 0xd8, 0x9c, 0x6c,
	0x62, 0x7b, 0x94, 0xa6, 0xac, 0xe0, 0x75, 0xa2, 0x71, 0xf3, 0xdb, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x0b, 0xd6, 0x42, 0x97, 0x55, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaybookClient is the client API for Playbook service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaybookClient interface {
	// 创建playbook项目
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	// 筛选playbook项目
	Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	// 获取playbook项目
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// 更新playbook项目
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// 删除playbook项目
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type playbookClient struct {
	cc *grpc.ClientConn
}

func NewPlaybookClient(cc *grpc.ClientConn) PlaybookClient {
	return &playbookClient{cc}
}

func (c *playbookClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/proto.Playbook/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbookClient) Filter(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, "/proto.Playbook/Filter", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbookClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/proto.Playbook/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbookClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.Playbook/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playbookClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/proto.Playbook/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaybookServer is the server API for Playbook service.
type PlaybookServer interface {
	// 创建playbook项目
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	// 筛选playbook项目
	Filter(context.Context, *FilterRequest) (*FilterResponse, error)
	// 获取playbook项目
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// 更新playbook项目
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// 删除playbook项目
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedPlaybookServer can be embedded to have forward compatible implementations.
type UnimplementedPlaybookServer struct {
}

func (*UnimplementedPlaybookServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedPlaybookServer) Filter(ctx context.Context, req *FilterRequest) (*FilterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Filter not implemented")
}
func (*UnimplementedPlaybookServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedPlaybookServer) Update(ctx context.Context, req *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedPlaybookServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterPlaybookServer(s *grpc.Server, srv PlaybookServer) {
	s.RegisterService(&_Playbook_serviceDesc, srv)
}

func _Playbook_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Playbook/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playbook_Filter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookServer).Filter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Playbook/Filter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookServer).Filter(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playbook_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Playbook/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playbook_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Playbook/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Playbook_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaybookServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Playbook/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaybookServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Playbook_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Playbook",
	HandlerType: (*PlaybookServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Playbook_Create_Handler,
		},
		{
			MethodName: "Filter",
			Handler:    _Playbook_Filter_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Playbook_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Playbook_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Playbook_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playbook/playbook.proto",
}
