// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmdb/cmdb.proto

package cmdb

import (
	context "context"
	fmt "fmt"
	common "git.fogcdn.top/axe/protos/goout/common"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 业务拓扑对象
type TopologyObject struct {
	// 业务ID
	BkInstId int32 `protobuf:"varint,1,opt,name=bk_inst_id,json=bkInstId,proto3" json:"bk_inst_id,omitempty"`
	// 业务名称
	BkInstName string `protobuf:"bytes,2,opt,name=bk_inst_name,json=bkInstName,proto3" json:"bk_inst_name,omitempty"`
	// 对象ID
	BkObjId string `protobuf:"bytes,3,opt,name=bk_obj_id,json=bkObjId,proto3" json:"bk_obj_id,omitempty"`
	// 对象名称
	BkObjName string `protobuf:"bytes,4,opt,name=bk_obj_name,json=bkObjName,proto3" json:"bk_obj_name,omitempty"`
	// 子对象
	Child                []*TopologyObject `protobuf:"bytes,5,rep,name=child,proto3" json:"child,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TopologyObject) Reset()         { *m = TopologyObject{} }
func (m *TopologyObject) String() string { return proto.CompactTextString(m) }
func (*TopologyObject) ProtoMessage()    {}
func (*TopologyObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{0}
}

func (m *TopologyObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopologyObject.Unmarshal(m, b)
}
func (m *TopologyObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopologyObject.Marshal(b, m, deterministic)
}
func (m *TopologyObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopologyObject.Merge(m, src)
}
func (m *TopologyObject) XXX_Size() int {
	return xxx_messageInfo_TopologyObject.Size(m)
}
func (m *TopologyObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TopologyObject.DiscardUnknown(m)
}

var xxx_messageInfo_TopologyObject proto.InternalMessageInfo

func (m *TopologyObject) GetBkInstId() int32 {
	if m != nil {
		return m.BkInstId
	}
	return 0
}

func (m *TopologyObject) GetBkInstName() string {
	if m != nil {
		return m.BkInstName
	}
	return ""
}

func (m *TopologyObject) GetBkObjId() string {
	if m != nil {
		return m.BkObjId
	}
	return ""
}

func (m *TopologyObject) GetBkObjName() string {
	if m != nil {
		return m.BkObjName
	}
	return ""
}

func (m *TopologyObject) GetChild() []*TopologyObject {
	if m != nil {
		return m.Child
	}
	return nil
}

// 拓扑实例请求
type InstanceTopologyRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstanceTopologyRequest) Reset()         { *m = InstanceTopologyRequest{} }
func (m *InstanceTopologyRequest) String() string { return proto.CompactTextString(m) }
func (*InstanceTopologyRequest) ProtoMessage()    {}
func (*InstanceTopologyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{1}
}

func (m *InstanceTopologyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceTopologyRequest.Unmarshal(m, b)
}
func (m *InstanceTopologyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceTopologyRequest.Marshal(b, m, deterministic)
}
func (m *InstanceTopologyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceTopologyRequest.Merge(m, src)
}
func (m *InstanceTopologyRequest) XXX_Size() int {
	return xxx_messageInfo_InstanceTopologyRequest.Size(m)
}
func (m *InstanceTopologyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceTopologyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceTopologyRequest proto.InternalMessageInfo

// 拓扑实例请求返回
type InstanceTopologyResponse struct {
	// 业务拓扑对象
	Instance *TopologyObject `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// 状态码
	Status               *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *InstanceTopologyResponse) Reset()         { *m = InstanceTopologyResponse{} }
func (m *InstanceTopologyResponse) String() string { return proto.CompactTextString(m) }
func (*InstanceTopologyResponse) ProtoMessage()    {}
func (*InstanceTopologyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{2}
}

func (m *InstanceTopologyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstanceTopologyResponse.Unmarshal(m, b)
}
func (m *InstanceTopologyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstanceTopologyResponse.Marshal(b, m, deterministic)
}
func (m *InstanceTopologyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstanceTopologyResponse.Merge(m, src)
}
func (m *InstanceTopologyResponse) XXX_Size() int {
	return xxx_messageInfo_InstanceTopologyResponse.Size(m)
}
func (m *InstanceTopologyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InstanceTopologyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InstanceTopologyResponse proto.InternalMessageInfo

func (m *InstanceTopologyResponse) GetInstance() *TopologyObject {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *InstanceTopologyResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 主机
type HostObject struct {
	// 内网IP
	BkHostInnerip        string   `protobuf:"bytes,1,opt,name=bk_host_innerip,json=bkHostInnerip,proto3" json:"bk_host_innerip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HostObject) Reset()         { *m = HostObject{} }
func (m *HostObject) String() string { return proto.CompactTextString(m) }
func (*HostObject) ProtoMessage()    {}
func (*HostObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{3}
}

func (m *HostObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostObject.Unmarshal(m, b)
}
func (m *HostObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostObject.Marshal(b, m, deterministic)
}
func (m *HostObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostObject.Merge(m, src)
}
func (m *HostObject) XXX_Size() int {
	return xxx_messageInfo_HostObject.Size(m)
}
func (m *HostObject) XXX_DiscardUnknown() {
	xxx_messageInfo_HostObject.DiscardUnknown(m)
}

var xxx_messageInfo_HostObject proto.InternalMessageInfo

func (m *HostObject) GetBkHostInnerip() string {
	if m != nil {
		return m.BkHostInnerip
	}
	return ""
}

// 模块
type ModuleObject struct {
	// 模块名
	BkModuleName string `protobuf:"bytes,1,opt,name=bk_module_name,json=bkModuleName,proto3" json:"bk_module_name,omitempty"`
	// 模块ID
	BkModuleId           int32    `protobuf:"varint,2,opt,name=bk_module_id,json=bkModuleId,proto3" json:"bk_module_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModuleObject) Reset()         { *m = ModuleObject{} }
func (m *ModuleObject) String() string { return proto.CompactTextString(m) }
func (*ModuleObject) ProtoMessage()    {}
func (*ModuleObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{4}
}

func (m *ModuleObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModuleObject.Unmarshal(m, b)
}
func (m *ModuleObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModuleObject.Marshal(b, m, deterministic)
}
func (m *ModuleObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModuleObject.Merge(m, src)
}
func (m *ModuleObject) XXX_Size() int {
	return xxx_messageInfo_ModuleObject.Size(m)
}
func (m *ModuleObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ModuleObject.DiscardUnknown(m)
}

var xxx_messageInfo_ModuleObject proto.InternalMessageInfo

func (m *ModuleObject) GetBkModuleName() string {
	if m != nil {
		return m.BkModuleName
	}
	return ""
}

func (m *ModuleObject) GetBkModuleId() int32 {
	if m != nil {
		return m.BkModuleId
	}
	return 0
}

// 集群
type SetObject struct {
	// 集群名
	BkSetName string `protobuf:"bytes,1,opt,name=bk_set_name,json=bkSetName,proto3" json:"bk_set_name,omitempty"`
	// 集群ID
	BkSetId              int32    `protobuf:"varint,2,opt,name=bk_set_id,json=bkSetId,proto3" json:"bk_set_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetObject) Reset()         { *m = SetObject{} }
func (m *SetObject) String() string { return proto.CompactTextString(m) }
func (*SetObject) ProtoMessage()    {}
func (*SetObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{5}
}

func (m *SetObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetObject.Unmarshal(m, b)
}
func (m *SetObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetObject.Marshal(b, m, deterministic)
}
func (m *SetObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetObject.Merge(m, src)
}
func (m *SetObject) XXX_Size() int {
	return xxx_messageInfo_SetObject.Size(m)
}
func (m *SetObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SetObject.DiscardUnknown(m)
}

var xxx_messageInfo_SetObject proto.InternalMessageInfo

func (m *SetObject) GetBkSetName() string {
	if m != nil {
		return m.BkSetName
	}
	return ""
}

func (m *SetObject) GetBkSetId() int32 {
	if m != nil {
		return m.BkSetId
	}
	return 0
}

// 区域
type ZoneObject struct {
	// 区域ID
	BkInstId             int32    `protobuf:"varint,1,opt,name=bk_inst_id,json=bkInstId,proto3" json:"bk_inst_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneObject) Reset()         { *m = ZoneObject{} }
func (m *ZoneObject) String() string { return proto.CompactTextString(m) }
func (*ZoneObject) ProtoMessage()    {}
func (*ZoneObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{6}
}

func (m *ZoneObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneObject.Unmarshal(m, b)
}
func (m *ZoneObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneObject.Marshal(b, m, deterministic)
}
func (m *ZoneObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneObject.Merge(m, src)
}
func (m *ZoneObject) XXX_Size() int {
	return xxx_messageInfo_ZoneObject.Size(m)
}
func (m *ZoneObject) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneObject.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneObject proto.InternalMessageInfo

func (m *ZoneObject) GetBkInstId() int32 {
	if m != nil {
		return m.BkInstId
	}
	return 0
}

// 业务
type BizObject struct {
	// 业务名
	BkBizName string `protobuf:"bytes,1,opt,name=bk_biz_name,json=bkBizName,proto3" json:"bk_biz_name,omitempty"`
	// 业务ID
	BkBizId              int32    `protobuf:"varint,2,opt,name=bk_biz_id,json=bkBizId,proto3" json:"bk_biz_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BizObject) Reset()         { *m = BizObject{} }
func (m *BizObject) String() string { return proto.CompactTextString(m) }
func (*BizObject) ProtoMessage()    {}
func (*BizObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{7}
}

func (m *BizObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BizObject.Unmarshal(m, b)
}
func (m *BizObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BizObject.Marshal(b, m, deterministic)
}
func (m *BizObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BizObject.Merge(m, src)
}
func (m *BizObject) XXX_Size() int {
	return xxx_messageInfo_BizObject.Size(m)
}
func (m *BizObject) XXX_DiscardUnknown() {
	xxx_messageInfo_BizObject.DiscardUnknown(m)
}

var xxx_messageInfo_BizObject proto.InternalMessageInfo

func (m *BizObject) GetBkBizName() string {
	if m != nil {
		return m.BkBizName
	}
	return ""
}

func (m *BizObject) GetBkBizId() int32 {
	if m != nil {
		return m.BkBizId
	}
	return 0
}

// 主机内容信息
type HostInfoObject struct {
	// 主机对象
	Host *HostObject `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// 模块对象
	Module []*ModuleObject `protobuf:"bytes,2,rep,name=module,proto3" json:"module,omitempty"`
	// 集群对象
	Set []*SetObject `protobuf:"bytes,3,rep,name=set,proto3" json:"set,omitempty"`
	// 业务对象
	Biz                  []*BizObject `protobuf:"bytes,4,rep,name=biz,proto3" json:"biz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *HostInfoObject) Reset()         { *m = HostInfoObject{} }
func (m *HostInfoObject) String() string { return proto.CompactTextString(m) }
func (*HostInfoObject) ProtoMessage()    {}
func (*HostInfoObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{8}
}

func (m *HostInfoObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HostInfoObject.Unmarshal(m, b)
}
func (m *HostInfoObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HostInfoObject.Marshal(b, m, deterministic)
}
func (m *HostInfoObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HostInfoObject.Merge(m, src)
}
func (m *HostInfoObject) XXX_Size() int {
	return xxx_messageInfo_HostInfoObject.Size(m)
}
func (m *HostInfoObject) XXX_DiscardUnknown() {
	xxx_messageInfo_HostInfoObject.DiscardUnknown(m)
}

var xxx_messageInfo_HostInfoObject proto.InternalMessageInfo

func (m *HostInfoObject) GetHost() *HostObject {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *HostInfoObject) GetModule() []*ModuleObject {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *HostInfoObject) GetSet() []*SetObject {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *HostInfoObject) GetBiz() []*BizObject {
	if m != nil {
		return m.Biz
	}
	return nil
}

// 查找主机请求
type SearchHostRequest struct {
	// 分页信息
	Paging *common.Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	// 主机对象
	Host *HostObject `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	// 模块对象
	Module *ModuleObject `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	// 集群对象
	Set *SetObject `protobuf:"bytes,4,opt,name=set,proto3" json:"set,omitempty"`
	// 业务对象
	Biz *BizObject `protobuf:"bytes,5,opt,name=biz,proto3" json:"biz,omitempty"`
	// 区域对象
	Zone                 *ZoneObject `protobuf:"bytes,6,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SearchHostRequest) Reset()         { *m = SearchHostRequest{} }
func (m *SearchHostRequest) String() string { return proto.CompactTextString(m) }
func (*SearchHostRequest) ProtoMessage()    {}
func (*SearchHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{9}
}

func (m *SearchHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchHostRequest.Unmarshal(m, b)
}
func (m *SearchHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchHostRequest.Marshal(b, m, deterministic)
}
func (m *SearchHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchHostRequest.Merge(m, src)
}
func (m *SearchHostRequest) XXX_Size() int {
	return xxx_messageInfo_SearchHostRequest.Size(m)
}
func (m *SearchHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchHostRequest proto.InternalMessageInfo

func (m *SearchHostRequest) GetPaging() *common.Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *SearchHostRequest) GetHost() *HostObject {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *SearchHostRequest) GetModule() *ModuleObject {
	if m != nil {
		return m.Module
	}
	return nil
}

func (m *SearchHostRequest) GetSet() *SetObject {
	if m != nil {
		return m.Set
	}
	return nil
}

func (m *SearchHostRequest) GetBiz() *BizObject {
	if m != nil {
		return m.Biz
	}
	return nil
}

func (m *SearchHostRequest) GetZone() *ZoneObject {
	if m != nil {
		return m.Zone
	}
	return nil
}

// 查找主机请求返回
type SearchHostResponse struct {
	// 分页信息
	Paging *common.Paging `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	// 状态码
	Status *common.ResponseStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// 主机信息
	Info                 []*HostInfoObject `protobuf:"bytes,3,rep,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SearchHostResponse) Reset()         { *m = SearchHostResponse{} }
func (m *SearchHostResponse) String() string { return proto.CompactTextString(m) }
func (*SearchHostResponse) ProtoMessage()    {}
func (*SearchHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{10}
}

func (m *SearchHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchHostResponse.Unmarshal(m, b)
}
func (m *SearchHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchHostResponse.Marshal(b, m, deterministic)
}
func (m *SearchHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchHostResponse.Merge(m, src)
}
func (m *SearchHostResponse) XXX_Size() int {
	return xxx_messageInfo_SearchHostResponse.Size(m)
}
func (m *SearchHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchHostResponse proto.InternalMessageInfo

func (m *SearchHostResponse) GetPaging() *common.Paging {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *SearchHostResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SearchHostResponse) GetInfo() []*HostInfoObject {
	if m != nil {
		return m.Info
	}
	return nil
}

// 导入主机请求
type ImportHostRequest struct {
	// csv文件下载路径
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImportHostRequest) Reset()         { *m = ImportHostRequest{} }
func (m *ImportHostRequest) String() string { return proto.CompactTextString(m) }
func (*ImportHostRequest) ProtoMessage()    {}
func (*ImportHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{11}
}

func (m *ImportHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportHostRequest.Unmarshal(m, b)
}
func (m *ImportHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportHostRequest.Marshal(b, m, deterministic)
}
func (m *ImportHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportHostRequest.Merge(m, src)
}
func (m *ImportHostRequest) XXX_Size() int {
	return xxx_messageInfo_ImportHostRequest.Size(m)
}
func (m *ImportHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ImportHostRequest proto.InternalMessageInfo

func (m *ImportHostRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// 导入主机请求返回
type ImportHostResponse struct {
	// 状态码
	Status               *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ImportHostResponse) Reset()         { *m = ImportHostResponse{} }
func (m *ImportHostResponse) String() string { return proto.CompactTextString(m) }
func (*ImportHostResponse) ProtoMessage()    {}
func (*ImportHostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{12}
}

func (m *ImportHostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportHostResponse.Unmarshal(m, b)
}
func (m *ImportHostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportHostResponse.Marshal(b, m, deterministic)
}
func (m *ImportHostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportHostResponse.Merge(m, src)
}
func (m *ImportHostResponse) XXX_Size() int {
	return xxx_messageInfo_ImportHostResponse.Size(m)
}
func (m *ImportHostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportHostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ImportHostResponse proto.InternalMessageInfo

func (m *ImportHostResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

// 选择主机请求
type ChooseHostRequest struct {
	// 集群ID
	BkSetId int32 `protobuf:"varint,1,opt,name=bk_set_id,json=bkSetId,proto3" json:"bk_set_id,omitempty"`
	// 模块ID
	BkModuleId           []int32  `protobuf:"varint,2,rep,packed,name=bk_module_id,json=bkModuleId,proto3" json:"bk_module_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChooseHostRequest) Reset()         { *m = ChooseHostRequest{} }
func (m *ChooseHostRequest) String() string { return proto.CompactTextString(m) }
func (*ChooseHostRequest) ProtoMessage()    {}
func (*ChooseHostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_02e1f4eaffd389ae, []int{13}
}

func (m *ChooseHostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChooseHostRequest.Unmarshal(m, b)
}
func (m *ChooseHostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChooseHostRequest.Marshal(b, m, deterministic)
}
func (m *ChooseHostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChooseHostRequest.Merge(m, src)
}
func (m *ChooseHostRequest) XXX_Size() int {
	return xxx_messageInfo_ChooseHostRequest.Size(m)
}
func (m *ChooseHostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChooseHostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChooseHostRequest proto.InternalMessageInfo

func (m *ChooseHostRequest) GetBkSetId() int32 {
	if m != nil {
		return m.BkSetId
	}
	return 0
}

func (m *ChooseHostRequest) GetBkModuleId() []int32 {
	if m != nil {
		return m.BkModuleId
	}
	return nil
}

func init() {
	proto.RegisterType((*TopologyObject)(nil), "cmdb.TopologyObject")
	proto.RegisterType((*InstanceTopologyRequest)(nil), "cmdb.InstanceTopologyRequest")
	proto.RegisterType((*InstanceTopologyResponse)(nil), "cmdb.InstanceTopologyResponse")
	proto.RegisterType((*HostObject)(nil), "cmdb.HostObject")
	proto.RegisterType((*ModuleObject)(nil), "cmdb.ModuleObject")
	proto.RegisterType((*SetObject)(nil), "cmdb.SetObject")
	proto.RegisterType((*ZoneObject)(nil), "cmdb.ZoneObject")
	proto.RegisterType((*BizObject)(nil), "cmdb.BizObject")
	proto.RegisterType((*HostInfoObject)(nil), "cmdb.HostInfoObject")
	proto.RegisterType((*SearchHostRequest)(nil), "cmdb.SearchHostRequest")
	proto.RegisterType((*SearchHostResponse)(nil), "cmdb.SearchHostResponse")
	proto.RegisterType((*ImportHostRequest)(nil), "cmdb.ImportHostRequest")
	proto.RegisterType((*ImportHostResponse)(nil), "cmdb.ImportHostResponse")
	proto.RegisterType((*ChooseHostRequest)(nil), "cmdb.ChooseHostRequest")
}

func init() { proto.RegisterFile("cmdb/cmdb.proto", fileDescriptor_02e1f4eaffd389ae) }

var fileDescriptor_02e1f4eaffd389ae = []byte{
	// 866 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xd6, 0xfa, 0xaf, 0xf5, 0x49, 0xc8, 0xcf, 0xb4, 0x90, 0xad, 0x5b, 0x4a, 0xba, 0xaa, 0xaa,
	0x10, 0x11, 0x2f, 0x04, 0xc4, 0x25, 0x17, 0x2e, 0x12, 0x58, 0x02, 0x0a, 0x1b, 0x40, 0xa8, 0xaa,
	0x64, 0xed, 0xec, 0x4e, 0xd6, 0x93, 0xf5, 0xce, 0x59, 0xbc, 0xe3, 0xa6, 0x58, 0x5c, 0xc1, 0x35,
	0x57, 0x48, 0x3c, 0x03, 0xbc, 0x41, 0x14, 0x89, 0xa7, 0xe0, 0x01, 0x90, 0x50, 0x24, 0x78, 0x05,
	0xee, 0xd0, 0xcc, 0xec, 0x9f, 0xe3, 0x04, 0xb9, 0x37, 0xf6, 0x6a, 0xbe, 0xef, 0x9c, 0xef, 0x9c,
	0xef, 0x9c, 0xd9, 0x85, 0xcd, 0x20, 0x09, 0xa9, 0xab, 0x7e, 0xfa, 0xe9, 0x14, 0x25, 0x92, 0x96,
	0x7a, 0xee, 0x6d, 0x05, 0x98, 0x24, 0x28, 0x5c, 0x3f, 0xe5, 0xe6, 0xbc, 0x77, 0x2f, 0x42, 0x8c,
	0x26, 0x4c, 0x9d, 0xb8, 0xbe, 0x10, 0x28, 0x7d, 0xc9, 0x51, 0x64, 0x39, 0xfa, 0x96, 0xfe, 0x0b,
	0x0e, 0x22, 0x26, 0x0e, 0xb2, 0x53, 0x3f, 0x8a, 0xd8, 0xd4, 0xc5, 0x54, 0x33, 0xae, 0x60, 0xbf,
	0x1f, 0x71, 0x39, 0x9e, 0xd1, 0x7e, 0x80, 0x89, 0x9b, 0x9c, 0x72, 0x19, 0xe3, 0xa9, 0x1b, 0xe1,
	0x81, 0x06, 0x0f, 0x9e, 0xfb, 0x13, 0x1e, 0xfa, 0x12, 0xa7, 0x99, 0x5b, 0x3e, 0x9a, 0x38, 0xe7,
	0xcc, 0x82, 0x8d, 0x2f, 0x31, 0xc5, 0x09, 0x46, 0xdf, 0x3d, 0xa1, 0x27, 0x2c, 0x90, 0xe4, 0x1e,
	0x00, 0x8d, 0x47, 0x5c, 0x64, 0x72, 0xc4, 0x43, 0xdb, 0xda, 0xb5, 0xf6, 0xda, 0xde, 0x4d, 0x1a,
	0x0f, 0x45, 0x26, 0x87, 0x21, 0xd9, 0x85, 0xf5, 0x02, 0x15, 0x7e, 0xc2, 0xec, 0xc6, 0xae, 0xb5,
	0xd7, 0xf5, 0xc0, 0xe0, 0x9f, 0xf9, 0x09, 0x23, 0x3d, 0xe8, 0xd2, 0x78, 0x84, 0xf4, 0x44, 0x85,
	0x37, 0x35, 0x7c, 0x83, 0xc6, 0x4f, 0xe8, 0xc9, 0x30, 0x24, 0xf7, 0x61, 0x2d, 0xc7, 0x74, 0x70,
	0x4b, 0xa3, 0x5d, 0x8d, 0xea, 0xd8, 0x7d, 0x68, 0x07, 0x63, 0x3e, 0x09, 0xed, 0xf6, 0x6e, 0x73,
	0x6f, 0xed, 0xf0, 0x76, 0x5f, 0xdb, 0xb8, 0x58, 0xa0, 0x67, 0x28, 0xce, 0x1d, 0xd8, 0x51, 0x9a,
	0xbe, 0x08, 0x58, 0x41, 0xf0, 0xd8, 0xb7, 0x33, 0x96, 0x49, 0xe7, 0x7b, 0xb0, 0x97, 0xa1, 0x2c,
	0x45, 0x91, 0x31, 0xf2, 0x36, 0xdc, 0xe4, 0x39, 0xa6, 0x9b, 0xbb, 0x4e, 0xa5, 0x64, 0x91, 0x3e,
	0x74, 0x32, 0xe9, 0xcb, 0x59, 0xa6, 0x9b, 0x5d, 0x3b, 0x7c, 0xad, 0x6f, 0x46, 0xd9, 0x2f, 0x72,
	0x1e, 0x69, 0xd4, 0xcb, 0x59, 0xce, 0x7b, 0x00, 0x1f, 0x63, 0x26, 0x73, 0x3b, 0x1f, 0xc1, 0x26,
	0x8d, 0x47, 0x63, 0x54, 0x76, 0x0a, 0xc1, 0xa6, 0x3c, 0xd5, 0xb2, 0x5d, 0xef, 0x15, 0x1a, 0x2b,
	0xda, 0xd0, 0x1c, 0x3a, 0x5f, 0xc3, 0xfa, 0xa7, 0x18, 0xce, 0x26, 0x2c, 0x8f, 0x7b, 0x08, 0x1b,
	0x34, 0x1e, 0x25, 0xfa, 0xc8, 0xb8, 0x65, 0xc2, 0xd6, 0x69, 0x6c, 0x78, 0xda, 0x30, 0x33, 0x8e,
	0x9c, 0xc5, 0x43, 0x5d, 0x61, 0x5b, 0x8d, 0xc3, 0x70, 0x86, 0xa1, 0xf3, 0x11, 0x74, 0x8f, 0x58,
	0x51, 0x8c, 0xf1, 0x3f, 0x63, 0xb2, 0x9e, 0xb1, 0x4b, 0xe3, 0x23, 0x56, 0x9f, 0x9d, 0xc2, 0xcb,
	0x5c, 0x37, 0x34, 0x3a, 0x0c, 0x9d, 0x7d, 0x80, 0xa7, 0x28, 0xd8, 0x2a, 0x5b, 0xa2, 0x44, 0x07,
	0x7c, 0xbe, 0x20, 0x4a, 0xf9, 0xfc, 0x92, 0xe8, 0x80, 0xcf, 0x6b, 0xa2, 0x0a, 0xaf, 0x8b, 0x0e,
	0xf8, 0x7c, 0x18, 0x3a, 0xbf, 0x5a, 0xb0, 0x61, 0x5c, 0x3a, 0xc6, 0xd2, 0x98, 0x96, 0x72, 0x33,
	0x1f, 0xde, 0x96, 0x19, 0x5e, 0x65, 0xb8, 0xa7, 0x51, 0xb2, 0x0f, 0x1d, 0xe3, 0x8a, 0xdd, 0xd0,
	0xab, 0x44, 0x0c, 0xaf, 0x6e, 0xb1, 0x97, 0x33, 0xc8, 0x03, 0x68, 0x66, 0x4c, 0xda, 0x4d, 0x4d,
	0xdc, 0x34, 0xc4, 0xd2, 0x33, 0x4f, 0x61, 0x8a, 0x42, 0xf9, 0xdc, 0x6e, 0xd5, 0x29, 0x65, 0x87,
	0x9e, 0xc2, 0x9c, 0x7f, 0x2d, 0xd8, 0x3e, 0x62, 0xfe, 0x34, 0x18, 0xab, 0x62, 0xf2, 0x55, 0x24,
	0x8f, 0xa0, 0x93, 0xfa, 0x11, 0x17, 0x51, 0x5e, 0xef, 0x46, 0xb1, 0x3c, 0x9f, 0xeb, 0x53, 0x2f,
	0x47, 0xcb, 0xae, 0x1a, 0x2b, 0x76, 0xd5, 0xd4, 0xbc, 0x15, 0xba, 0x6a, 0x69, 0xe2, 0xff, 0x76,
	0xd5, 0xae, 0x53, 0x16, 0xbb, 0x52, 0x75, 0xcd, 0x51, 0x30, 0xbb, 0x53, 0xaf, 0xab, 0xda, 0x03,
	0x4f, 0xa3, 0xce, 0x2f, 0x16, 0x90, 0x7a, 0xef, 0xf9, 0x5d, 0x5b, 0xb5, 0xf9, 0x97, 0xbc, 0x61,
	0x64, 0x0f, 0x5a, 0x5c, 0x1c, 0x63, 0x3e, 0xb1, 0xdb, 0x95, 0x59, 0xd5, 0x9a, 0x78, 0x9a, 0xe1,
	0x7c, 0x00, 0xdb, 0xc3, 0x24, 0xc5, 0xa9, 0xac, 0xcf, 0xe4, 0x4d, 0x68, 0xce, 0xa6, 0x13, 0xb3,
	0x88, 0x83, 0x9d, 0xbf, 0xfe, 0x7c, 0xe3, 0xd6, 0xfe, 0xe6, 0x57, 0xde, 0x27, 0x17, 0x67, 0x3f,
	0xfd, 0xf3, 0xe3, 0xef, 0x17, 0x67, 0xe7, 0x7f, 0xff, 0x76, 0xfe, 0x8d, 0xe5, 0x29, 0x8e, 0xf3,
	0x21, 0x90, 0x7a, 0x7c, 0xde, 0x57, 0x55, 0xaf, 0xb5, 0xd2, 0x1b, 0xe1, 0x0b, 0xd8, 0x7e, 0x3c,
	0x46, 0xcc, 0x58, 0xbd, 0x8a, 0x85, 0xbb, 0x66, 0x2d, 0xdc, 0xb5, 0x2b, 0xae, 0x75, 0x73, 0xf1,
	0x5a, 0x1f, 0x9e, 0x35, 0xa0, 0xf5, 0x38, 0x09, 0x29, 0x91, 0xb0, 0x75, 0xf9, 0x5d, 0x47, 0x5e,
	0x37, 0x8e, 0x5c, 0xf3, 0x7a, 0xec, 0xdd, 0xbf, 0x0e, 0x36, 0xc5, 0x3b, 0x0f, 0x7e, 0xf8, 0xe3,
	0xe2, 0xe7, 0xc6, 0x5d, 0x72, 0xc7, 0x7d, 0xfe, 0x8e, 0xfe, 0x90, 0xb9, 0xfc, 0xb2, 0xc2, 0x33,
	0x80, 0x6a, 0xde, 0x64, 0xa7, 0xd8, 0xae, 0x4b, 0xdb, 0xdf, 0xb3, 0x97, 0x81, 0x5c, 0xe3, 0xae,
	0xd6, 0x78, 0x95, 0xdc, 0x2a, 0x35, 0xb2, 0x2a, 0xdf, 0x33, 0x80, 0xca, 0xf5, 0x22, 0xfb, 0xd2,
	0x1c, 0x8b, 0xec, 0xcb, 0x03, 0xba, 0x22, 0x3b, 0x2f, 0x49, 0x83, 0x01, 0xf4, 0x24, 0xa6, 0xfd,
	0x63, 0x8c, 0x82, 0x50, 0xf4, 0xfd, 0x17, 0xcc, 0x7c, 0x0b, 0x33, 0x9d, 0xed, 0xe9, 0xc3, 0x88,
	0xcb, 0x02, 0x93, 0x98, 0xba, 0xfe, 0x0b, 0xe6, 0x1a, 0xdc, 0x8d, 0x10, 0x67, 0x52, 0xa7, 0xa3,
	0x1d, 0x7d, 0xf4, 0xee, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x97, 0xdd, 0xd7, 0x45, 0xed, 0x07,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CmdbClient is the client API for Cmdb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CmdbClient interface {
	// 实例拓扑
	InstanceTopology(ctx context.Context, in *InstanceTopologyRequest, opts ...grpc.CallOption) (*InstanceTopologyResponse, error)
	// 查找主机
	SearchHost(ctx context.Context, in *SearchHostRequest, opts ...grpc.CallOption) (*SearchHostResponse, error)
	// 导入主机
	ImportHost(ctx context.Context, in *ImportHostRequest, opts ...grpc.CallOption) (*ImportHostResponse, error)
}

type cmdbClient struct {
	cc *grpc.ClientConn
}

func NewCmdbClient(cc *grpc.ClientConn) CmdbClient {
	return &cmdbClient{cc}
}

func (c *cmdbClient) InstanceTopology(ctx context.Context, in *InstanceTopologyRequest, opts ...grpc.CallOption) (*InstanceTopologyResponse, error) {
	out := new(InstanceTopologyResponse)
	err := c.cc.Invoke(ctx, "/cmdb.Cmdb/InstanceTopology", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdbClient) SearchHost(ctx context.Context, in *SearchHostRequest, opts ...grpc.CallOption) (*SearchHostResponse, error) {
	out := new(SearchHostResponse)
	err := c.cc.Invoke(ctx, "/cmdb.Cmdb/SearchHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmdbClient) ImportHost(ctx context.Context, in *ImportHostRequest, opts ...grpc.CallOption) (*ImportHostResponse, error) {
	out := new(ImportHostResponse)
	err := c.cc.Invoke(ctx, "/cmdb.Cmdb/ImportHost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmdbServer is the server API for Cmdb service.
type CmdbServer interface {
	// 实例拓扑
	InstanceTopology(context.Context, *InstanceTopologyRequest) (*InstanceTopologyResponse, error)
	// 查找主机
	SearchHost(context.Context, *SearchHostRequest) (*SearchHostResponse, error)
	// 导入主机
	ImportHost(context.Context, *ImportHostRequest) (*ImportHostResponse, error)
}

// UnimplementedCmdbServer can be embedded to have forward compatible implementations.
type UnimplementedCmdbServer struct {
}

func (*UnimplementedCmdbServer) InstanceTopology(ctx context.Context, req *InstanceTopologyRequest) (*InstanceTopologyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstanceTopology not implemented")
}
func (*UnimplementedCmdbServer) SearchHost(ctx context.Context, req *SearchHostRequest) (*SearchHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchHost not implemented")
}
func (*UnimplementedCmdbServer) ImportHost(ctx context.Context, req *ImportHostRequest) (*ImportHostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportHost not implemented")
}

func RegisterCmdbServer(s *grpc.Server, srv CmdbServer) {
	s.RegisterService(&_Cmdb_serviceDesc, srv)
}

func _Cmdb_InstanceTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdbServer).InstanceTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdb.Cmdb/InstanceTopology",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdbServer).InstanceTopology(ctx, req.(*InstanceTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmdb_SearchHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdbServer).SearchHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdb.Cmdb/SearchHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdbServer).SearchHost(ctx, req.(*SearchHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cmdb_ImportHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmdbServer).ImportHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdb.Cmdb/ImportHost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmdbServer).ImportHost(ctx, req.(*ImportHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cmdb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdb.Cmdb",
	HandlerType: (*CmdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstanceTopology",
			Handler:    _Cmdb_InstanceTopology_Handler,
		},
		{
			MethodName: "SearchHost",
			Handler:    _Cmdb_SearchHost_Handler,
		},
		{
			MethodName: "ImportHost",
			Handler:    _Cmdb_ImportHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmdb/cmdb.proto",
}
