// Code generated by protoc-gen-go. DO NOT EDIT.
// source: callback/callback.proto

package callback

import (
	context "context"
	fmt "fmt"
	common "git.fogcdn.top/axe/protos/goout/common"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// cmdb事件请求
type CmdbEventRequest struct {
	// 事件类型
	EventType string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// 触发动作
	Action string `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	// 事件相关的实体，如集群set
	ObjType string `protobuf:"bytes,3,opt,name=obj_type,json=objType,proto3" json:"obj_type,omitempty"`
	// 事件的变更数据
	Data                 []*CmdbEventData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CmdbEventRequest) Reset()         { *m = CmdbEventRequest{} }
func (m *CmdbEventRequest) String() string { return proto.CompactTextString(m) }
func (*CmdbEventRequest) ProtoMessage()    {}
func (*CmdbEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0902222c118453, []int{0}
}

func (m *CmdbEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdbEventRequest.Unmarshal(m, b)
}
func (m *CmdbEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdbEventRequest.Marshal(b, m, deterministic)
}
func (m *CmdbEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdbEventRequest.Merge(m, src)
}
func (m *CmdbEventRequest) XXX_Size() int {
	return xxx_messageInfo_CmdbEventRequest.Size(m)
}
func (m *CmdbEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdbEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CmdbEventRequest proto.InternalMessageInfo

func (m *CmdbEventRequest) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *CmdbEventRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CmdbEventRequest) GetObjType() string {
	if m != nil {
		return m.ObjType
	}
	return ""
}

func (m *CmdbEventRequest) GetData() []*CmdbEventData {
	if m != nil {
		return m.Data
	}
	return nil
}

// cmdb事件请求返回
type CmdbEventResponse struct {
	// 返回状态码
	Status               *common.ResponseStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CmdbEventResponse) Reset()         { *m = CmdbEventResponse{} }
func (m *CmdbEventResponse) String() string { return proto.CompactTextString(m) }
func (*CmdbEventResponse) ProtoMessage()    {}
func (*CmdbEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0902222c118453, []int{1}
}

func (m *CmdbEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdbEventResponse.Unmarshal(m, b)
}
func (m *CmdbEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdbEventResponse.Marshal(b, m, deterministic)
}
func (m *CmdbEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdbEventResponse.Merge(m, src)
}
func (m *CmdbEventResponse) XXX_Size() int {
	return xxx_messageInfo_CmdbEventResponse.Size(m)
}
func (m *CmdbEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdbEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CmdbEventResponse proto.InternalMessageInfo

func (m *CmdbEventResponse) GetStatus() *common.ResponseStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type CmdbEventData struct {
	// 时间触发前的实体数据
	CurData map[string]*any.Any `protobuf:"bytes,1,rep,name=cur_data,json=curData,proto3" json:"cur_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 时间触发后的实体数据
	PreData              map[string]*any.Any `protobuf:"bytes,2,rep,name=pre_data,json=preData,proto3" json:"pre_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CmdbEventData) Reset()         { *m = CmdbEventData{} }
func (m *CmdbEventData) String() string { return proto.CompactTextString(m) }
func (*CmdbEventData) ProtoMessage()    {}
func (*CmdbEventData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6a0902222c118453, []int{2}
}

func (m *CmdbEventData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdbEventData.Unmarshal(m, b)
}
func (m *CmdbEventData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdbEventData.Marshal(b, m, deterministic)
}
func (m *CmdbEventData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdbEventData.Merge(m, src)
}
func (m *CmdbEventData) XXX_Size() int {
	return xxx_messageInfo_CmdbEventData.Size(m)
}
func (m *CmdbEventData) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdbEventData.DiscardUnknown(m)
}

var xxx_messageInfo_CmdbEventData proto.InternalMessageInfo

func (m *CmdbEventData) GetCurData() map[string]*any.Any {
	if m != nil {
		return m.CurData
	}
	return nil
}

func (m *CmdbEventData) GetPreData() map[string]*any.Any {
	if m != nil {
		return m.PreData
	}
	return nil
}

func init() {
	proto.RegisterType((*CmdbEventRequest)(nil), "callback.CmdbEventRequest")
	proto.RegisterType((*CmdbEventResponse)(nil), "callback.CmdbEventResponse")
	proto.RegisterType((*CmdbEventData)(nil), "callback.CmdbEventData")
	proto.RegisterMapType((map[string]*any.Any)(nil), "callback.CmdbEventData.CurDataEntry")
	proto.RegisterMapType((map[string]*any.Any)(nil), "callback.CmdbEventData.PreDataEntry")
}

func init() { proto.RegisterFile("callback/callback.proto", fileDescriptor_6a0902222c118453) }

var fileDescriptor_6a0902222c118453 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xcf, 0x6e, 0xd3, 0x30,
	0x18, 0x57, 0xd2, 0xd1, 0xb5, 0x5f, 0x41, 0x2a, 0x16, 0xea, 0xba, 0x0c, 0xd0, 0x88, 0x38, 0x54,
	0x43, 0xb2, 0x45, 0xb9, 0xa0, 0x5d, 0x10, 0x94, 0x5d, 0x38, 0x4d, 0x81, 0x13, 0x97, 0xc9, 0x49,
	0xbd, 0xa8, 0x5b, 0xea, 0xcf, 0xc4, 0x4e, 0xb5, 0x5c, 0x79, 0x03, 0xc4, 0xb3, 0xf0, 0x24, 0xbc,
	0x02, 0x0f, 0x82, 0x62, 0x3b, 0x21, 0x48, 0x83, 0xcb, 0x4e, 0xf6, 0xef, 0xfb, 0x7d, 0xfe, 0xf9,
	0xf7, 0xfd, 0x81, 0x83, 0x8c, 0x17, 0x45, 0xca, 0xb3, 0x6b, 0xd6, 0x5e, 0xa8, 0x2a, 0xd1, 0x20,
	0x19, 0xb5, 0x38, 0x9a, 0x66, 0xb8, 0xdd, 0xa2, 0x64, 0x5c, 0x6d, 0x1c, 0x17, 0x3d, 0xce, 0x11,
	0xf3, 0x42, 0x34, 0x11, 0xc6, 0xa5, 0x44, 0xc3, 0xcd, 0x06, 0xa5, 0xf6, 0xec, 0xa1, 0x67, 0x2d,
	0x4a, 0xab, 0x4b, 0xc6, 0x65, 0xed, 0xa8, 0xf8, 0x5b, 0x00, 0xd3, 0xd5, 0x76, 0x9d, 0x9e, 0xed,
	0x84, 0x34, 0x89, 0xf8, 0x52, 0x09, 0x6d, 0xc8, 0x13, 0x00, 0xd1, 0xe0, 0x0b, 0x53, 0x2b, 0x31,
	0x0f, 0x8e, 0x83, 0xc5, 0x38, 0x19, 0xdb, 0xc8, 0xa7, 0x5a, 0x09, 0x32, 0x83, 0x21, 0xcf, 0x1a,
	0xfd, 0x79, 0x68, 0x29, 0x8f, 0xc8, 0x21, 0x8c, 0x30, 0xbd, 0x72, 0x8f, 0x06, 0x96, 0xd9, 0xc7,
	0xf4, 0xca, 0x3e, 0x79, 0x01, 0x7b, 0x6b, 0x6e, 0xf8, 0x7c, 0xef, 0x78, 0xb0, 0x98, 0x2c, 0x0f,
	0x68, 0x57, 0x5a, 0xf7, 0xf7, 0x7b, 0x6e, 0x78, 0x62, 0x93, 0xe2, 0x15, 0x3c, 0xec, 0x59, 0xd2,
	0x0a, 0xa5, 0x16, 0x84, 0xc2, 0x50, 0x1b, 0x6e, 0x2a, 0x6d, 0xfd, 0x4c, 0x96, 0x33, 0xea, 0x9a,
	0x40, 0xdb, 0x8c, 0x8f, 0x96, 0x4d, 0x7c, 0x56, 0xfc, 0x23, 0x84, 0x07, 0x7f, 0x89, 0x93, 0x37,
	0x30, 0xca, 0xaa, 0xf2, 0xc2, 0xfa, 0x08, 0xac, 0x8f, 0xe7, 0xff, 0xf0, 0x41, 0x57, 0x55, 0xd9,
	0x9c, 0x67, 0xd2, 0x94, 0x75, 0xb2, 0x9f, 0x39, 0xd4, 0x08, 0xa8, 0x52, 0x38, 0x81, 0xf0, 0xff,
	0x02, 0xe7, 0xa5, 0xe8, 0x09, 0x28, 0x87, 0xa2, 0x73, 0xb8, 0xdf, 0x57, 0x26, 0x53, 0x18, 0x5c,
	0x8b, 0xda, 0x37, 0xb8, 0xb9, 0x92, 0x13, 0xb8, 0xb7, 0xe3, 0x45, 0x25, 0x6c, 0x67, 0x27, 0xcb,
	0x47, 0xd4, 0x4d, 0x8e, 0xb6, 0x93, 0xa3, 0x6f, 0x65, 0x9d, 0xb8, 0x94, 0xd3, 0xf0, 0x75, 0xd0,
	0x28, 0xf6, 0xbf, 0xba, 0xbb, 0xe2, 0x52, 0xc3, 0x68, 0xe5, 0x6b, 0x22, 0x39, 0x8c, 0xbb, 0xb2,
	0x48, 0x74, 0x4b, 0xad, 0x7e, 0x61, 0xa2, 0xa3, 0x5b, 0x39, 0x37, 0x97, 0xf8, 0xd9, 0xd7, 0x9f,
	0xbf, 0xbe, 0x87, 0x47, 0xf1, 0x8c, 0xed, 0x5e, 0xb2, 0x3f, 0xcb, 0xdd, 0xe6, 0x9d, 0x06, 0x27,
	0xef, 0x3e, 0xc0, 0x53, 0x83, 0x8a, 0x5e, 0x62, 0x9e, 0xad, 0x25, 0xe5, 0x37, 0xde, 0x9e, 0xee,
	0x64, 0x3f, 0x2f, 0xf2, 0x8d, 0x69, 0x79, 0x83, 0x8a, 0xf1, 0x1b, 0xbf, 0xce, 0x9a, 0xe5, 0x88,
	0x95, 0xe9, 0x84, 0xd3, 0xa1, 0x0d, 0xbf, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x0d, 0xed,
	0x82, 0x48, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CallbackClient is the client API for Callback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CallbackClient interface {
	// 接收cmdb的事件推送
	CmdbEvent(ctx context.Context, in *CmdbEventRequest, opts ...grpc.CallOption) (*CmdbEventResponse, error)
}

type callbackClient struct {
	cc *grpc.ClientConn
}

func NewCallbackClient(cc *grpc.ClientConn) CallbackClient {
	return &callbackClient{cc}
}

func (c *callbackClient) CmdbEvent(ctx context.Context, in *CmdbEventRequest, opts ...grpc.CallOption) (*CmdbEventResponse, error) {
	out := new(CmdbEventResponse)
	err := c.cc.Invoke(ctx, "/callback.Callback/CmdbEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CallbackServer is the server API for Callback service.
type CallbackServer interface {
	// 接收cmdb的事件推送
	CmdbEvent(context.Context, *CmdbEventRequest) (*CmdbEventResponse, error)
}

// UnimplementedCallbackServer can be embedded to have forward compatible implementations.
type UnimplementedCallbackServer struct {
}

func (*UnimplementedCallbackServer) CmdbEvent(ctx context.Context, req *CmdbEventRequest) (*CmdbEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CmdbEvent not implemented")
}

func RegisterCallbackServer(s *grpc.Server, srv CallbackServer) {
	s.RegisterService(&_Callback_serviceDesc, srv)
}

func _Callback_CmdbEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdbEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CallbackServer).CmdbEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/callback.Callback/CmdbEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CallbackServer).CmdbEvent(ctx, req.(*CmdbEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Callback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "callback.Callback",
	HandlerType: (*CallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CmdbEvent",
			Handler:    _Callback_CmdbEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "callback/callback.proto",
}
