// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/api.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 接口状态码
type StatusCode int32

const (
	StatusCode_SUCCESS          StatusCode = 0
	StatusCode_INVALID_ARGUMENT StatusCode = 400
	StatusCode_ACCESS_DENIED    StatusCode = 403
)

var StatusCode_name = map[int32]string{
	0:   "SUCCESS",
	400: "INVALID_ARGUMENT",
	403: "ACCESS_DENIED",
}

var StatusCode_value = map[string]int32{
	"SUCCESS":          0,
	"INVALID_ARGUMENT": 400,
	"ACCESS_DENIED":    403,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{0}
}

// 分页
type Paging struct {
	TotalPage            int32    `protobuf:"varint,1,opt,name=total_page,json=totalPage,proto3" json:"total_page,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage              int32    `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Paging) Reset()         { *m = Paging{} }
func (m *Paging) String() string { return proto.CompactTextString(m) }
func (*Paging) ProtoMessage()    {}
func (*Paging) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{0}
}

func (m *Paging) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paging.Unmarshal(m, b)
}
func (m *Paging) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paging.Marshal(b, m, deterministic)
}
func (m *Paging) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paging.Merge(m, src)
}
func (m *Paging) XXX_Size() int {
	return xxx_messageInfo_Paging.Size(m)
}
func (m *Paging) XXX_DiscardUnknown() {
	xxx_messageInfo_Paging.DiscardUnknown(m)
}

var xxx_messageInfo_Paging proto.InternalMessageInfo

func (m *Paging) GetTotalPage() int32 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

func (m *Paging) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Paging) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

// 接口返回状态码
type ResponseStatus struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=common.StatusCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponseStatus) Reset()         { *m = ResponseStatus{} }
func (m *ResponseStatus) String() string { return proto.CompactTextString(m) }
func (*ResponseStatus) ProtoMessage()    {}
func (*ResponseStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_71edda3932b293bf, []int{1}
}

func (m *ResponseStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseStatus.Unmarshal(m, b)
}
func (m *ResponseStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseStatus.Marshal(b, m, deterministic)
}
func (m *ResponseStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseStatus.Merge(m, src)
}
func (m *ResponseStatus) XXX_Size() int {
	return xxx_messageInfo_ResponseStatus.Size(m)
}
func (m *ResponseStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseStatus proto.InternalMessageInfo

func (m *ResponseStatus) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_SUCCESS
}

func (m *ResponseStatus) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("common.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*Paging)(nil), "common.Paging")
	proto.RegisterType((*ResponseStatus)(nil), "common.ResponseStatus")
}

func init() { proto.RegisterFile("common/api.proto", fileDescriptor_71edda3932b293bf) }

var fileDescriptor_71edda3932b293bf = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xd1, 0x4a, 0xf3, 0x30,
	0x14, 0x80, 0xff, 0xfd, 0x9b, 0xad, 0x3b, 0xe2, 0x28, 0x07, 0x84, 0x09, 0x0a, 0xb2, 0x8b, 0x21,
	0x5e, 0xb4, 0xa0, 0x4f, 0x50, 0xdb, 0x2a, 0x05, 0x2d, 0x23, 0x75, 0xbb, 0xf0, 0xa6, 0xc4, 0x36,
	0x86, 0x82, 0xed, 0x09, 0x4d, 0x06, 0x7b, 0x0c, 0xc1, 0x17, 0x16, 0x13, 0x8b, 0x77, 0xc9, 0xf7,
	0x7d, 0x49, 0x0e, 0x81, 0xa0, 0xa6, 0xae, 0xa3, 0x3e, 0xe2, 0xaa, 0x0d, 0xd5, 0x40, 0x86, 0xd0,
	0x73, 0x64, 0xb5, 0x03, 0x6f, 0xc3, 0x65, 0xdb, 0x4b, 0xbc, 0x04, 0x30, 0x64, 0xf8, 0x47, 0xa5,
	0xb8, 0x14, 0xcb, 0xc9, 0xd5, 0xe4, 0xfa, 0x88, 0xcd, 0x2d, 0xd9, 0x70, 0x29, 0x10, 0x61, 0x66,
	0xc5, 0x7f, 0x2b, 0xec, 0x1a, 0xcf, 0xe1, 0x58, 0x89, 0xc1, 0x1d, 0x98, 0x5a, 0xee, 0x2b, 0x31,
	0xfc, 0xe4, 0x2b, 0x06, 0x0b, 0x26, 0xb4, 0xa2, 0x5e, 0x8b, 0xd2, 0x70, 0xb3, 0xd7, 0xb8, 0x86,
	0x59, 0x4d, 0x8d, 0xbb, 0x79, 0x71, 0x8b, 0xa1, 0x1b, 0x20, 0x74, 0x36, 0xa1, 0x46, 0x30, 0xeb,
	0x71, 0x09, 0x7e, 0x27, 0xb4, 0x1e, 0xdf, 0x9a, 0xb3, 0x71, 0x7b, 0x93, 0x02, 0xfc, 0xd5, 0x78,
	0x02, 0x7e, 0xb9, 0x4d, 0x92, 0xac, 0x2c, 0x83, 0x7f, 0x78, 0x06, 0x41, 0x5e, 0xec, 0xe2, 0xa7,
	0x3c, 0xad, 0x62, 0xf6, 0xb8, 0x7d, 0xce, 0x8a, 0x97, 0xe0, 0x73, 0x8a, 0x08, 0xa7, 0xb1, 0x4d,
	0xaa, 0x34, 0x2b, 0xf2, 0x2c, 0x0d, 0xbe, 0xa6, 0xf7, 0x0f, 0x70, 0x61, 0x48, 0x85, 0xef, 0x24,
	0xeb, 0xa6, 0x0f, 0xf9, 0x41, 0xb8, 0x1f, 0xd1, 0xbf, 0x03, 0xbd, 0xae, 0x65, 0x6b, 0x46, 0x6b,
	0x48, 0x45, 0xfc, 0x20, 0x22, 0x57, 0x44, 0x92, 0x68, 0x6f, 0x22, 0xd7, 0xbd, 0x79, 0x16, 0xde,
	0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xda, 0x28, 0x5e, 0xdc, 0x5c, 0x01, 0x00, 0x00,
}
