// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ironic/ironicCom.proto

package ironic

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *PageInfo) Validate() error {
	return nil
}
func (this *ScopeInfo) Validate() error {
	return nil
}
func (this *TimeScope) Validate() error {
	if this.BeginDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.BeginDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("BeginDate", err)
		}
	}
	if this.EndDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EndDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EndDate", err)
		}
	}
	return nil
}
func (this *TcpContReq) Validate() error {
	if this.ReqTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ReqTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ReqTime", err)
		}
	}
	return nil
}
func (this *TcpContRsp) Validate() error {
	if this.RspTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.RspTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("RspTime", err)
		}
	}
	return nil
}
